package com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric;

import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.ASN1ObjectIdentifier;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.bsi.BSIObjectIdentifiers;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.eac.EACObjectIdentifiers;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.nist.NISTObjectIdentifiers;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.sec.SECObjectIdentifiers;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.teletrust.TeleTrusTObjectIdentifiers;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.x9.X9ObjectIdentifiers;
import com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi;
import com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.config.ConfigurableProvider;
import com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.util.AsymmetricAlgorithmProvider;
import com.fis.ekyc.nfc.build_in.bouncycastle.util.Properties;
import java.util.HashMap;
import java.util.Map;

public class EC {
    private static final String PREFIX = "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.";
    /* access modifiers changed from: private */
    public static final Map<String, String> generalEcAttributes;

    public static class Mappings extends AsymmetricAlgorithmProvider {
        public void configure(ConfigurableProvider configurableProvider) {
            ConfigurableProvider configurableProvider2 = configurableProvider;
            configurableProvider2.addAlgorithm("AlgorithmParameters.EC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.AlgorithmParametersSpi");
            configurableProvider2.addAttributes("KeyAgreement.ECDH", EC.generalEcAttributes);
            configurableProvider2.addAlgorithm("KeyAgreement.ECDH", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DH");
            configurableProvider2.addAttributes("KeyAgreement.ECDHC", EC.generalEcAttributes);
            configurableProvider2.addAlgorithm("KeyAgreement.ECDHC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHC");
            configurableProvider2.addAttributes("KeyAgreement.ECCDH", EC.generalEcAttributes);
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDH", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHC");
            configurableProvider2.addAttributes("KeyAgreement.ECCDHU", EC.generalEcAttributes);
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHU", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUC");
            configurableProvider2.addAlgorithm("KeyAgreement.ECDHWITHSHA1KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA1KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA1KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA1KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECDHWITHSHA224KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA224KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA224KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA224KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECDHWITHSHA256KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA256KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA256KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA256KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECDHWITHSHA384KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA384KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA384KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA384KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECDHWITHSHA512KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA512KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA512KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA512KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier = X9ObjectIdentifiers.dhSinglePass_stdDH_sha1kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA1KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier2 = X9ObjectIdentifiers.dhSinglePass_cofactorDH_sha1kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier2, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA1KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier3 = SECObjectIdentifiers.dhSinglePass_stdDH_sha224kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier3, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA224KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier4 = SECObjectIdentifiers.dhSinglePass_cofactorDH_sha224kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier4, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA224KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier5 = SECObjectIdentifiers.dhSinglePass_stdDH_sha256kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier5, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA256KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier6 = SECObjectIdentifiers.dhSinglePass_cofactorDH_sha256kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier6, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA256KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier7 = SECObjectIdentifiers.dhSinglePass_stdDH_sha384kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier7, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA384KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier8 = SECObjectIdentifiers.dhSinglePass_cofactorDH_sha384kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier8, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA384KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier9 = SECObjectIdentifiers.dhSinglePass_stdDH_sha512kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier9, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA512KDFAndSharedInfo");
            ASN1ObjectIdentifier aSN1ObjectIdentifier10 = SECObjectIdentifiers.dhSinglePass_cofactorDH_sha512kdf_scheme;
            configurableProvider2.addAlgorithm("KeyAgreement", aSN1ObjectIdentifier10, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$CDHwithSHA512KDFAndSharedInfo");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA1CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA1CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA256CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA256CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA384CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA384CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHWITHSHA512CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHwithSHA512CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA1CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA1CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA224CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA224CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA256CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA256CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA384CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA384CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA512CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA512CKDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA1KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA1KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA224KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA224KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA256KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA256KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA384KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA384KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECCDHUWITHSHA512KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$DHUwithSHA512KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECKAEGWITHSHA1KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA1KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECKAEGWITHSHA224KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA224KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECKAEGWITHSHA256KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA256KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECKAEGWITHSHA384KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA384KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECKAEGWITHSHA512KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA512KDF");
            configurableProvider2.addAlgorithm("KeyAgreement", BSIObjectIdentifiers.ecka_eg_X963kdf_SHA1, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA1KDF");
            configurableProvider2.addAlgorithm("KeyAgreement", BSIObjectIdentifiers.ecka_eg_X963kdf_SHA224, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA224KDF");
            configurableProvider2.addAlgorithm("KeyAgreement", BSIObjectIdentifiers.ecka_eg_X963kdf_SHA256, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA256KDF");
            configurableProvider2.addAlgorithm("KeyAgreement", BSIObjectIdentifiers.ecka_eg_X963kdf_SHA384, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA384KDF");
            configurableProvider2.addAlgorithm("KeyAgreement", BSIObjectIdentifiers.ecka_eg_X963kdf_SHA512, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithSHA512KDF");
            configurableProvider2.addAlgorithm("KeyAgreement", BSIObjectIdentifiers.ecka_eg_X963kdf_RIPEMD160, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithRIPEMD160KDF");
            configurableProvider2.addAlgorithm("KeyAgreement.ECKAEGWITHRIPEMD160KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$ECKAEGwithRIPEMD160KDF");
            ASN1ObjectIdentifier aSN1ObjectIdentifier11 = X9ObjectIdentifiers.id_ecPublicKey;
            registerOid(configurableProvider2, aSN1ObjectIdentifier11, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier2, "EC", new KeyFactorySpi.EC());
            ASN1ObjectIdentifier aSN1ObjectIdentifier12 = X9ObjectIdentifiers.mqvSinglePass_sha1kdf_scheme;
            registerOid(configurableProvider2, aSN1ObjectIdentifier12, "ECMQV", new KeyFactorySpi.ECMQV());
            registerOid(configurableProvider2, aSN1ObjectIdentifier3, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier4, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier5, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier6, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier7, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier8, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier9, "EC", new KeyFactorySpi.EC());
            registerOid(configurableProvider2, aSN1ObjectIdentifier10, "EC", new KeyFactorySpi.EC());
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier11, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier2, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier3, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier4, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier5, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier6, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier7, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier8, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier9, "EC");
            registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier10, "EC");
            if (!Properties.isOverrideSet("com.fis.ekyc.nfc.build_in.bouncycastle.ec.disable_mqv")) {
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQV", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQV");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA1CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA1CKDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA224CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA224CKDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA256CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA256CKDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA384CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA384CKDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA512CKDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA512CKDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA1KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA1KDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA224KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA224KDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA256KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA256KDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA384KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA384KDF");
                configurableProvider2.addAlgorithm("KeyAgreement.ECMQVWITHSHA512KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA512KDF");
                configurableProvider2.addAlgorithm("KeyAgreement." + aSN1ObjectIdentifier12, "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA1KDFAndSharedInfo");
                StringBuilder sb2 = new StringBuilder();
                sb2.append("KeyAgreement.");
                ASN1ObjectIdentifier aSN1ObjectIdentifier13 = SECObjectIdentifiers.mqvSinglePass_sha224kdf_scheme;
                sb2.append(aSN1ObjectIdentifier13);
                configurableProvider2.addAlgorithm(sb2.toString(), "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA224KDFAndSharedInfo");
                StringBuilder sb3 = new StringBuilder();
                sb3.append("KeyAgreement.");
                ASN1ObjectIdentifier aSN1ObjectIdentifier14 = SECObjectIdentifiers.mqvSinglePass_sha256kdf_scheme;
                sb3.append(aSN1ObjectIdentifier14);
                configurableProvider2.addAlgorithm(sb3.toString(), "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA256KDFAndSharedInfo");
                StringBuilder sb4 = new StringBuilder();
                sb4.append("KeyAgreement.");
                ASN1ObjectIdentifier aSN1ObjectIdentifier15 = SECObjectIdentifiers.mqvSinglePass_sha384kdf_scheme;
                sb4.append(aSN1ObjectIdentifier15);
                configurableProvider2.addAlgorithm(sb4.toString(), "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA384KDFAndSharedInfo");
                StringBuilder sb5 = new StringBuilder();
                sb5.append("KeyAgreement.");
                ASN1ObjectIdentifier aSN1ObjectIdentifier16 = SECObjectIdentifiers.mqvSinglePass_sha512kdf_scheme;
                sb5.append(aSN1ObjectIdentifier16);
                configurableProvider2.addAlgorithm(sb5.toString(), "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi$MQVwithSHA512KDFAndSharedInfo");
                registerOid(configurableProvider2, aSN1ObjectIdentifier, "EC", new KeyFactorySpi.EC());
                registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier12, "EC");
                registerOid(configurableProvider2, aSN1ObjectIdentifier13, "ECMQV", new KeyFactorySpi.ECMQV());
                registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier14, "EC");
                registerOid(configurableProvider2, aSN1ObjectIdentifier14, "ECMQV", new KeyFactorySpi.ECMQV());
                registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier13, "EC");
                registerOid(configurableProvider2, aSN1ObjectIdentifier15, "ECMQV", new KeyFactorySpi.ECMQV());
                registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier15, "EC");
                registerOid(configurableProvider2, aSN1ObjectIdentifier16, "ECMQV", new KeyFactorySpi.ECMQV());
                registerOidAlgorithmParameters(configurableProvider2, aSN1ObjectIdentifier16, "EC");
                configurableProvider2.addAlgorithm("KeyFactory.ECMQV", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECMQV");
                configurableProvider2.addAlgorithm("KeyPairGenerator.ECMQV", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECMQV");
            }
            configurableProvider2.addAlgorithm("KeyFactory.EC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$EC");
            configurableProvider2.addAlgorithm("KeyFactory.ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECDSA");
            configurableProvider2.addAlgorithm("KeyFactory.ECDH", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECDH");
            configurableProvider2.addAlgorithm("KeyFactory.ECDHC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi$ECDHC");
            configurableProvider2.addAlgorithm("KeyPairGenerator.EC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC");
            configurableProvider2.addAlgorithm("KeyPairGenerator.ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDSA");
            configurableProvider2.addAlgorithm("KeyPairGenerator.ECDH", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDH");
            configurableProvider2.addAlgorithm("KeyPairGenerator.ECDHWITHSHA1KDF", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDH");
            configurableProvider2.addAlgorithm("KeyPairGenerator.ECDHC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDHC");
            configurableProvider2.addAlgorithm("KeyPairGenerator.ECIES", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$ECDH");
            configurableProvider2.addAlgorithm("Cipher.ECIES", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIES");
            configurableProvider2.addAlgorithm("Cipher.ECIESwithAES-CBC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithAESCBC");
            configurableProvider2.addAlgorithm("Cipher.ECIESWITHAES-CBC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithAESCBC");
            configurableProvider2.addAlgorithm("Cipher.ECIESwithDESEDE-CBC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithDESedeCBC");
            configurableProvider2.addAlgorithm("Cipher.ECIESWITHDESEDE-CBC", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher$ECIESwithDESedeCBC");
            configurableProvider2.addAlgorithm("Signature.ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA");
            configurableProvider2.addAlgorithm("Signature.NONEwithECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSAnone");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA1withECDSA", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.ECDSAwithSHA1", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA1WITHECDSA", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.ECDSAWITHSHA1", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA1WithECDSA", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.ECDSAWithSHA1", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.1.2.840.10045.4.1", "ECDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature." + TeleTrusTObjectIdentifiers.ecSignWithSha1, "ECDSA");
            configurableProvider2.addAlgorithm("Signature.ECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA");
            configurableProvider2.addAlgorithm("Signature.SHA1WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA");
            configurableProvider2.addAlgorithm("Signature.SHA224WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA224");
            configurableProvider2.addAlgorithm("Signature.SHA256WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA256");
            configurableProvider2.addAlgorithm("Signature.SHA384WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA384");
            configurableProvider2.addAlgorithm("Signature.SHA512WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSA512");
            configurableProvider2.addAlgorithm("Signature.SHA3-224WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_224");
            configurableProvider2.addAlgorithm("Signature.SHA3-256WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_256");
            configurableProvider2.addAlgorithm("Signature.SHA3-384WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_384");
            configurableProvider2.addAlgorithm("Signature.SHA3-512WITHECDDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDetDSASha3_512");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.DETECDSA", "ECDDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA1WITHDETECDSA", "SHA1WITHECDDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA224WITHDETECDSA", "SHA224WITHECDDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA256WITHDETECDSA", "SHA256WITHECDDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA384WITHDETECDSA", "SHA384WITHECDDSA");
            configurableProvider2.addAlgorithm("Alg.Alias.Signature.SHA512WITHDETECDSA", "SHA512WITHECDDSA");
            ConfigurableProvider configurableProvider3 = configurableProvider;
            addSignatureAlgorithm(configurableProvider3, "SHA224", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA224", X9ObjectIdentifiers.ecdsa_with_SHA224);
            addSignatureAlgorithm(configurableProvider3, "SHA256", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA256", X9ObjectIdentifiers.ecdsa_with_SHA256);
            addSignatureAlgorithm(configurableProvider3, "SHA384", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA384", X9ObjectIdentifiers.ecdsa_with_SHA384);
            addSignatureAlgorithm(configurableProvider3, "SHA512", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSA512", X9ObjectIdentifiers.ecdsa_with_SHA512);
            addSignatureAlgorithm(configurableProvider3, "SHA3-224", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_224", NISTObjectIdentifiers.id_ecdsa_with_sha3_224);
            addSignatureAlgorithm(configurableProvider3, "SHA3-256", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_256", NISTObjectIdentifiers.id_ecdsa_with_sha3_256);
            addSignatureAlgorithm(configurableProvider3, "SHA3-384", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_384", NISTObjectIdentifiers.id_ecdsa_with_sha3_384);
            addSignatureAlgorithm(configurableProvider3, "SHA3-512", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSASha3_512", NISTObjectIdentifiers.id_ecdsa_with_sha3_512);
            addSignatureAlgorithm(configurableProvider3, "RIPEMD160", "ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecDSARipeMD160", TeleTrusTObjectIdentifiers.ecSignWithRipemd160);
            configurableProvider2.addAlgorithm("Signature.SHA1WITHECNR", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR");
            configurableProvider2.addAlgorithm("Signature.SHA224WITHECNR", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR224");
            configurableProvider2.addAlgorithm("Signature.SHA256WITHECNR", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR256");
            configurableProvider2.addAlgorithm("Signature.SHA384WITHECNR", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR384");
            configurableProvider2.addAlgorithm("Signature.SHA512WITHECNR", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecNR512");
            ConfigurableProvider configurableProvider4 = configurableProvider;
            addSignatureAlgorithm(configurableProvider4, "SHA1", "CVC-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA", EACObjectIdentifiers.id_TA_ECDSA_SHA_1);
            addSignatureAlgorithm(configurableProvider4, "SHA224", "CVC-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA224", EACObjectIdentifiers.id_TA_ECDSA_SHA_224);
            addSignatureAlgorithm(configurableProvider4, "SHA256", "CVC-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA256", EACObjectIdentifiers.id_TA_ECDSA_SHA_256);
            addSignatureAlgorithm(configurableProvider4, "SHA384", "CVC-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA384", EACObjectIdentifiers.id_TA_ECDSA_SHA_384);
            addSignatureAlgorithm(configurableProvider4, "SHA512", "CVC-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA512", EACObjectIdentifiers.id_TA_ECDSA_SHA_512);
            addSignatureAlgorithm(configurableProvider4, "SHA1", "PLAIN-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA", BSIObjectIdentifiers.ecdsa_plain_SHA1);
            addSignatureAlgorithm(configurableProvider4, "SHA224", "PLAIN-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA224", BSIObjectIdentifiers.ecdsa_plain_SHA224);
            addSignatureAlgorithm(configurableProvider4, "SHA256", "PLAIN-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA256", BSIObjectIdentifiers.ecdsa_plain_SHA256);
            addSignatureAlgorithm(configurableProvider4, "SHA384", "PLAIN-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA384", BSIObjectIdentifiers.ecdsa_plain_SHA384);
            addSignatureAlgorithm(configurableProvider4, "SHA512", "PLAIN-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecCVCDSA512", BSIObjectIdentifiers.ecdsa_plain_SHA512);
            addSignatureAlgorithm(configurableProvider4, "RIPEMD160", "PLAIN-ECDSA", "com.fis.ekyc.nfc.build_in.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi$ecPlainDSARP160", BSIObjectIdentifiers.ecdsa_plain_RIPEMD160);
        }
    }

    static {
        HashMap hashMap = new HashMap();
        generalEcAttributes = hashMap;
        hashMap.put("SupportedKeyClasses", "java.security.interfaces.ECPublicKey|java.security.interfaces.ECPrivateKey");
        hashMap.put("SupportedKeyFormats", "PKCS#8|X.509");
    }
}
