package com.fis.ekyc.nfc.build_in.bouncycastle.pqc.crypto.sphincsplus;

import com.fis.ekyc.nfc.build_in.bouncycastle.pqc.crypto.sphincsplus.SPHINCSPlusEngine;
import com.fis.ekyc.nfc.build_in.bouncycastle.util.Integers;
import com.fis.ekyc.nfc.build_in.bouncycastle.util.Pack;
import java.util.HashMap;
import java.util.Map;

public class SPHINCSPlusParameters {
    private static final Map oidToParams;
    private static final Map paramsToOid;
    public static final SPHINCSPlusParameters sha256_128f;
    public static final SPHINCSPlusParameters sha256_128f_simple;
    public static final SPHINCSPlusParameters sha256_128s;
    public static final SPHINCSPlusParameters sha256_128s_simple;
    public static final SPHINCSPlusParameters sha256_192f;
    public static final SPHINCSPlusParameters sha256_192f_simple;
    public static final SPHINCSPlusParameters sha256_192s;
    public static final SPHINCSPlusParameters sha256_192s_simple;
    public static final SPHINCSPlusParameters sha256_256f;
    public static final SPHINCSPlusParameters sha256_256f_simple;
    public static final SPHINCSPlusParameters sha256_256s;
    public static final SPHINCSPlusParameters sha256_256s_simple;
    public static final SPHINCSPlusParameters shake256_128f;
    public static final SPHINCSPlusParameters shake256_128f_simple;
    public static final SPHINCSPlusParameters shake256_128s;
    public static final SPHINCSPlusParameters shake256_128s_simple;
    public static final SPHINCSPlusParameters shake256_192f;
    public static final SPHINCSPlusParameters shake256_192f_simple;
    public static final SPHINCSPlusParameters shake256_192s;
    public static final SPHINCSPlusParameters shake256_192s_simple;
    public static final SPHINCSPlusParameters shake256_256f;
    public static final SPHINCSPlusParameters shake256_256f_simple;
    public static final SPHINCSPlusParameters shake256_256s;
    public static final SPHINCSPlusParameters shake256_256s_simple;
    private static final Integer sphincsPlus_sha256_128f_robust;
    private static final Integer sphincsPlus_sha256_128f_simple;
    private static final Integer sphincsPlus_sha256_128s_robust;
    private static final Integer sphincsPlus_sha256_128s_simple;
    private static final Integer sphincsPlus_sha256_192f_robust;
    private static final Integer sphincsPlus_sha256_192f_simple;
    private static final Integer sphincsPlus_sha256_192s_robust;
    private static final Integer sphincsPlus_sha256_192s_simple;
    private static final Integer sphincsPlus_sha256_256f_robust;
    private static final Integer sphincsPlus_sha256_256f_simple;
    private static final Integer sphincsPlus_sha256_256s_robust;
    private static final Integer sphincsPlus_sha256_256s_simple;
    private static final Integer sphincsPlus_shake256_128f_robust;
    private static final Integer sphincsPlus_shake256_128f_simple;
    private static final Integer sphincsPlus_shake256_128s_robust;
    private static final Integer sphincsPlus_shake256_128s_simple;
    private static final Integer sphincsPlus_shake256_192f_robust;
    private static final Integer sphincsPlus_shake256_192f_simple;
    private static final Integer sphincsPlus_shake256_192s_robust;
    private static final Integer sphincsPlus_shake256_192s_simple;
    private static final Integer sphincsPlus_shake256_256f_robust;
    private static final Integer sphincsPlus_shake256_256f_simple;
    private static final Integer sphincsPlus_shake256_256s_robust;
    private static final Integer sphincsPlus_shake256_256s_simple;
    private final SPHINCSPlusEngine engine;
    private final String name;

    static {
        SPHINCSPlusParameters sPHINCSPlusParameters = new SPHINCSPlusParameters("sha256-128f-robust", new SPHINCSPlusEngine.Sha256Engine(true, 16, 16, 22, 6, 33, 66));
        sha256_128f = sPHINCSPlusParameters;
        SPHINCSPlusParameters sPHINCSPlusParameters2 = new SPHINCSPlusParameters("sha256-128s-robust", new SPHINCSPlusEngine.Sha256Engine(true, 16, 16, 7, 12, 14, 63));
        sha256_128s = sPHINCSPlusParameters2;
        SPHINCSPlusParameters sPHINCSPlusParameters3 = new SPHINCSPlusParameters("sha256-192f-robust", new SPHINCSPlusEngine.Sha256Engine(true, 24, 16, 22, 8, 33, 66));
        sha256_192f = sPHINCSPlusParameters3;
        SPHINCSPlusParameters sPHINCSPlusParameters4 = new SPHINCSPlusParameters("sha256-192s-robust", new SPHINCSPlusEngine.Sha256Engine(true, 24, 16, 7, 14, 17, 63));
        sha256_192s = sPHINCSPlusParameters4;
        SPHINCSPlusParameters sPHINCSPlusParameters5 = new SPHINCSPlusParameters("sha256-256f-robust", new SPHINCSPlusEngine.Sha256Engine(true, 32, 16, 17, 9, 35, 68));
        sha256_256f = sPHINCSPlusParameters5;
        SPHINCSPlusParameters sPHINCSPlusParameters6 = new SPHINCSPlusParameters("sha256-256s-robust", new SPHINCSPlusEngine.Sha256Engine(true, 32, 16, 8, 14, 22, 64));
        sha256_256s = sPHINCSPlusParameters6;
        SPHINCSPlusParameters sPHINCSPlusParameters7 = new SPHINCSPlusParameters("sha256-128f-simple", new SPHINCSPlusEngine.Sha256Engine(false, 16, 16, 22, 6, 33, 66));
        sha256_128f_simple = sPHINCSPlusParameters7;
        SPHINCSPlusParameters sPHINCSPlusParameters8 = sPHINCSPlusParameters7;
        SPHINCSPlusEngine.Sha256Engine sha256Engine = r8;
        SPHINCSPlusEngine.Sha256Engine sha256Engine2 = new SPHINCSPlusEngine.Sha256Engine(false, 16, 16, 7, 12, 14, 63);
        SPHINCSPlusParameters sPHINCSPlusParameters9 = new SPHINCSPlusParameters("sha256-128s-simple", sha256Engine);
        sha256_128s_simple = sPHINCSPlusParameters9;
        SPHINCSPlusParameters sPHINCSPlusParameters10 = sPHINCSPlusParameters9;
        SPHINCSPlusEngine.Sha256Engine sha256Engine3 = r8;
        SPHINCSPlusEngine.Sha256Engine sha256Engine4 = new SPHINCSPlusEngine.Sha256Engine(false, 24, 16, 22, 8, 33, 66);
        SPHINCSPlusParameters sPHINCSPlusParameters11 = new SPHINCSPlusParameters("sha256-192f-simple", sha256Engine3);
        sha256_192f_simple = sPHINCSPlusParameters11;
        SPHINCSPlusParameters sPHINCSPlusParameters12 = sPHINCSPlusParameters11;
        SPHINCSPlusEngine.Sha256Engine sha256Engine5 = r8;
        SPHINCSPlusEngine.Sha256Engine sha256Engine6 = new SPHINCSPlusEngine.Sha256Engine(false, 24, 16, 7, 14, 17, 63);
        SPHINCSPlusParameters sPHINCSPlusParameters13 = new SPHINCSPlusParameters("sha256-192s-simple", sha256Engine5);
        sha256_192s_simple = sPHINCSPlusParameters13;
        SPHINCSPlusParameters sPHINCSPlusParameters14 = sPHINCSPlusParameters13;
        SPHINCSPlusEngine.Sha256Engine sha256Engine7 = r8;
        SPHINCSPlusEngine.Sha256Engine sha256Engine8 = new SPHINCSPlusEngine.Sha256Engine(false, 32, 16, 17, 9, 35, 68);
        SPHINCSPlusParameters sPHINCSPlusParameters15 = new SPHINCSPlusParameters("sha256-256f-simple", sha256Engine7);
        sha256_256f_simple = sPHINCSPlusParameters15;
        SPHINCSPlusParameters sPHINCSPlusParameters16 = sPHINCSPlusParameters15;
        SPHINCSPlusEngine.Sha256Engine sha256Engine9 = r8;
        SPHINCSPlusEngine.Sha256Engine sha256Engine10 = new SPHINCSPlusEngine.Sha256Engine(false, 32, 16, 8, 14, 22, 64);
        SPHINCSPlusParameters sPHINCSPlusParameters17 = new SPHINCSPlusParameters("sha256-256s-simple", sha256Engine9);
        sha256_256s_simple = sPHINCSPlusParameters17;
        SPHINCSPlusParameters sPHINCSPlusParameters18 = sPHINCSPlusParameters17;
        SPHINCSPlusEngine.Shake256Engine shake256Engine = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine2 = new SPHINCSPlusEngine.Shake256Engine(true, 16, 16, 22, 6, 33, 66);
        SPHINCSPlusParameters sPHINCSPlusParameters19 = new SPHINCSPlusParameters("shake256-128f-robust", shake256Engine);
        shake256_128f = sPHINCSPlusParameters19;
        SPHINCSPlusParameters sPHINCSPlusParameters20 = sPHINCSPlusParameters19;
        SPHINCSPlusEngine.Shake256Engine shake256Engine3 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine4 = new SPHINCSPlusEngine.Shake256Engine(true, 16, 16, 7, 12, 14, 63);
        SPHINCSPlusParameters sPHINCSPlusParameters21 = new SPHINCSPlusParameters("shake256-128s-robust", shake256Engine3);
        shake256_128s = sPHINCSPlusParameters21;
        SPHINCSPlusParameters sPHINCSPlusParameters22 = sPHINCSPlusParameters21;
        SPHINCSPlusEngine.Shake256Engine shake256Engine5 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine6 = new SPHINCSPlusEngine.Shake256Engine(true, 24, 16, 22, 8, 33, 66);
        SPHINCSPlusParameters sPHINCSPlusParameters23 = new SPHINCSPlusParameters("shake256-192f-robust", shake256Engine5);
        shake256_192f = sPHINCSPlusParameters23;
        SPHINCSPlusParameters sPHINCSPlusParameters24 = sPHINCSPlusParameters23;
        SPHINCSPlusEngine.Shake256Engine shake256Engine7 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine8 = new SPHINCSPlusEngine.Shake256Engine(true, 24, 16, 7, 14, 17, 63);
        SPHINCSPlusParameters sPHINCSPlusParameters25 = new SPHINCSPlusParameters("shake256-192s-robust", shake256Engine7);
        shake256_192s = sPHINCSPlusParameters25;
        SPHINCSPlusParameters sPHINCSPlusParameters26 = sPHINCSPlusParameters25;
        SPHINCSPlusEngine.Shake256Engine shake256Engine9 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine10 = new SPHINCSPlusEngine.Shake256Engine(true, 32, 16, 17, 9, 35, 68);
        SPHINCSPlusParameters sPHINCSPlusParameters27 = new SPHINCSPlusParameters("shake256-256f-robust", shake256Engine9);
        shake256_256f = sPHINCSPlusParameters27;
        SPHINCSPlusParameters sPHINCSPlusParameters28 = sPHINCSPlusParameters27;
        SPHINCSPlusEngine.Shake256Engine shake256Engine11 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine12 = new SPHINCSPlusEngine.Shake256Engine(true, 32, 16, 8, 14, 22, 64);
        SPHINCSPlusParameters sPHINCSPlusParameters29 = new SPHINCSPlusParameters("shake256-256s-robust", shake256Engine11);
        shake256_256s = sPHINCSPlusParameters29;
        SPHINCSPlusParameters sPHINCSPlusParameters30 = sPHINCSPlusParameters29;
        SPHINCSPlusEngine.Shake256Engine shake256Engine13 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine14 = new SPHINCSPlusEngine.Shake256Engine(false, 16, 16, 22, 6, 33, 66);
        SPHINCSPlusParameters sPHINCSPlusParameters31 = new SPHINCSPlusParameters("shake256-128f-simple", shake256Engine13);
        shake256_128f_simple = sPHINCSPlusParameters31;
        SPHINCSPlusParameters sPHINCSPlusParameters32 = sPHINCSPlusParameters31;
        SPHINCSPlusEngine.Shake256Engine shake256Engine15 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine16 = new SPHINCSPlusEngine.Shake256Engine(false, 16, 16, 7, 12, 14, 63);
        SPHINCSPlusParameters sPHINCSPlusParameters33 = new SPHINCSPlusParameters("shake256-128s-simple", shake256Engine15);
        shake256_128s_simple = sPHINCSPlusParameters33;
        SPHINCSPlusParameters sPHINCSPlusParameters34 = sPHINCSPlusParameters33;
        SPHINCSPlusEngine.Shake256Engine shake256Engine17 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine18 = new SPHINCSPlusEngine.Shake256Engine(false, 24, 16, 22, 8, 33, 66);
        SPHINCSPlusParameters sPHINCSPlusParameters35 = new SPHINCSPlusParameters("shake256-192f-simple", shake256Engine17);
        shake256_192f_simple = sPHINCSPlusParameters35;
        SPHINCSPlusParameters sPHINCSPlusParameters36 = sPHINCSPlusParameters35;
        SPHINCSPlusEngine.Shake256Engine shake256Engine19 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine20 = new SPHINCSPlusEngine.Shake256Engine(false, 24, 16, 7, 14, 17, 63);
        SPHINCSPlusParameters sPHINCSPlusParameters37 = new SPHINCSPlusParameters("shake256-192s-simple", shake256Engine19);
        shake256_192s_simple = sPHINCSPlusParameters37;
        SPHINCSPlusParameters sPHINCSPlusParameters38 = sPHINCSPlusParameters37;
        SPHINCSPlusEngine.Shake256Engine shake256Engine21 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine22 = new SPHINCSPlusEngine.Shake256Engine(false, 32, 16, 17, 9, 35, 68);
        SPHINCSPlusParameters sPHINCSPlusParameters39 = new SPHINCSPlusParameters("shake256-256f-simple", shake256Engine21);
        shake256_256f_simple = sPHINCSPlusParameters39;
        SPHINCSPlusParameters sPHINCSPlusParameters40 = sPHINCSPlusParameters39;
        SPHINCSPlusEngine.Shake256Engine shake256Engine23 = r8;
        SPHINCSPlusEngine.Shake256Engine shake256Engine24 = new SPHINCSPlusEngine.Shake256Engine(false, 32, 16, 8, 14, 22, 64);
        SPHINCSPlusParameters sPHINCSPlusParameters41 = new SPHINCSPlusParameters("shake256-256s-simple", shake256Engine23);
        shake256_256s_simple = sPHINCSPlusParameters41;
        Integer valueOf = Integers.valueOf(65793);
        sphincsPlus_sha256_128f_robust = valueOf;
        Integer valueOf2 = Integers.valueOf(65794);
        sphincsPlus_sha256_128s_robust = valueOf2;
        Integer valueOf3 = Integers.valueOf(65795);
        sphincsPlus_sha256_192f_robust = valueOf3;
        Integer valueOf4 = Integers.valueOf(65796);
        sphincsPlus_sha256_192s_robust = valueOf4;
        Integer valueOf5 = Integers.valueOf(65797);
        sphincsPlus_sha256_256f_robust = valueOf5;
        Integer valueOf6 = Integers.valueOf(65798);
        sphincsPlus_sha256_256s_robust = valueOf6;
        Integer valueOf7 = Integers.valueOf(66049);
        sphincsPlus_sha256_128f_simple = valueOf7;
        Integer valueOf8 = Integers.valueOf(66050);
        sphincsPlus_sha256_128s_simple = valueOf8;
        Integer valueOf9 = Integers.valueOf(66051);
        sphincsPlus_sha256_192f_simple = valueOf9;
        SPHINCSPlusParameters sPHINCSPlusParameters42 = sPHINCSPlusParameters41;
        Integer valueOf10 = Integers.valueOf(66052);
        sphincsPlus_sha256_192s_simple = valueOf10;
        Integer num = valueOf10;
        Integer valueOf11 = Integers.valueOf(66053);
        sphincsPlus_sha256_256f_simple = valueOf11;
        Integer num2 = valueOf11;
        Integer valueOf12 = Integers.valueOf(66054);
        sphincsPlus_sha256_256s_simple = valueOf12;
        Integer num3 = valueOf12;
        Integer valueOf13 = Integers.valueOf(131329);
        sphincsPlus_shake256_128f_robust = valueOf13;
        Integer num4 = valueOf13;
        Integer valueOf14 = Integers.valueOf(131330);
        sphincsPlus_shake256_128s_robust = valueOf14;
        Integer num5 = valueOf14;
        Integer valueOf15 = Integers.valueOf(131331);
        sphincsPlus_shake256_192f_robust = valueOf15;
        Integer num6 = valueOf15;
        Integer valueOf16 = Integers.valueOf(131332);
        sphincsPlus_shake256_192s_robust = valueOf16;
        Integer num7 = valueOf16;
        Integer valueOf17 = Integers.valueOf(131333);
        sphincsPlus_shake256_256f_robust = valueOf17;
        Integer num8 = valueOf17;
        Integer valueOf18 = Integers.valueOf(131334);
        sphincsPlus_shake256_256s_robust = valueOf18;
        Integer num9 = valueOf18;
        Integer valueOf19 = Integers.valueOf(131585);
        sphincsPlus_shake256_128f_simple = valueOf19;
        Integer num10 = valueOf19;
        Integer valueOf20 = Integers.valueOf(131586);
        sphincsPlus_shake256_128s_simple = valueOf20;
        Integer num11 = valueOf20;
        Integer valueOf21 = Integers.valueOf(131587);
        sphincsPlus_shake256_192f_simple = valueOf21;
        Integer num12 = valueOf21;
        Integer valueOf22 = Integers.valueOf(131588);
        sphincsPlus_shake256_192s_simple = valueOf22;
        Integer num13 = valueOf22;
        Integer valueOf23 = Integers.valueOf(131589);
        sphincsPlus_shake256_256f_simple = valueOf23;
        Integer num14 = valueOf23;
        Integer valueOf24 = Integers.valueOf(131590);
        sphincsPlus_shake256_256s_simple = valueOf24;
        Integer num15 = valueOf24;
        HashMap hashMap = new HashMap();
        oidToParams = hashMap;
        Integer num16 = valueOf9;
        HashMap hashMap2 = new HashMap();
        paramsToOid = hashMap2;
        hashMap.put(valueOf, sPHINCSPlusParameters);
        hashMap.put(valueOf2, sPHINCSPlusParameters2);
        hashMap.put(valueOf3, sPHINCSPlusParameters3);
        hashMap.put(valueOf4, sPHINCSPlusParameters4);
        hashMap.put(valueOf5, sPHINCSPlusParameters5);
        hashMap.put(valueOf6, sPHINCSPlusParameters6);
        SPHINCSPlusParameters sPHINCSPlusParameters43 = sPHINCSPlusParameters6;
        hashMap.put(valueOf7, sPHINCSPlusParameters8);
        hashMap.put(valueOf8, sPHINCSPlusParameters10);
        SPHINCSPlusParameters sPHINCSPlusParameters44 = sPHINCSPlusParameters12;
        Integer num17 = valueOf8;
        Integer num18 = num16;
        hashMap.put(num18, sPHINCSPlusParameters44);
        SPHINCSPlusParameters sPHINCSPlusParameters45 = sPHINCSPlusParameters44;
        SPHINCSPlusParameters sPHINCSPlusParameters46 = sPHINCSPlusParameters14;
        Integer num19 = num18;
        Integer num20 = num;
        hashMap.put(num20, sPHINCSPlusParameters46);
        SPHINCSPlusParameters sPHINCSPlusParameters47 = sPHINCSPlusParameters46;
        SPHINCSPlusParameters sPHINCSPlusParameters48 = sPHINCSPlusParameters16;
        Integer num21 = num20;
        Integer num22 = num2;
        hashMap.put(num22, sPHINCSPlusParameters48);
        SPHINCSPlusParameters sPHINCSPlusParameters49 = sPHINCSPlusParameters48;
        SPHINCSPlusParameters sPHINCSPlusParameters50 = sPHINCSPlusParameters18;
        Integer num23 = num22;
        Integer num24 = num3;
        hashMap.put(num24, sPHINCSPlusParameters50);
        SPHINCSPlusParameters sPHINCSPlusParameters51 = sPHINCSPlusParameters50;
        SPHINCSPlusParameters sPHINCSPlusParameters52 = sPHINCSPlusParameters20;
        Integer num25 = num24;
        Integer num26 = num4;
        hashMap.put(num26, sPHINCSPlusParameters52);
        SPHINCSPlusParameters sPHINCSPlusParameters53 = sPHINCSPlusParameters52;
        SPHINCSPlusParameters sPHINCSPlusParameters54 = sPHINCSPlusParameters22;
        Integer num27 = num26;
        Integer num28 = num5;
        hashMap.put(num28, sPHINCSPlusParameters54);
        SPHINCSPlusParameters sPHINCSPlusParameters55 = sPHINCSPlusParameters54;
        SPHINCSPlusParameters sPHINCSPlusParameters56 = sPHINCSPlusParameters24;
        Integer num29 = num28;
        Integer num30 = num6;
        hashMap.put(num30, sPHINCSPlusParameters56);
        SPHINCSPlusParameters sPHINCSPlusParameters57 = sPHINCSPlusParameters56;
        SPHINCSPlusParameters sPHINCSPlusParameters58 = sPHINCSPlusParameters26;
        Integer num31 = num30;
        Integer num32 = num7;
        hashMap.put(num32, sPHINCSPlusParameters58);
        SPHINCSPlusParameters sPHINCSPlusParameters59 = sPHINCSPlusParameters58;
        SPHINCSPlusParameters sPHINCSPlusParameters60 = sPHINCSPlusParameters28;
        Integer num33 = num32;
        Integer num34 = num8;
        hashMap.put(num34, sPHINCSPlusParameters60);
        SPHINCSPlusParameters sPHINCSPlusParameters61 = sPHINCSPlusParameters60;
        SPHINCSPlusParameters sPHINCSPlusParameters62 = sPHINCSPlusParameters30;
        Integer num35 = num34;
        Integer num36 = num9;
        hashMap.put(num36, sPHINCSPlusParameters62);
        SPHINCSPlusParameters sPHINCSPlusParameters63 = sPHINCSPlusParameters62;
        SPHINCSPlusParameters sPHINCSPlusParameters64 = sPHINCSPlusParameters32;
        Integer num37 = num36;
        Integer num38 = num10;
        hashMap.put(num38, sPHINCSPlusParameters64);
        SPHINCSPlusParameters sPHINCSPlusParameters65 = sPHINCSPlusParameters64;
        SPHINCSPlusParameters sPHINCSPlusParameters66 = sPHINCSPlusParameters34;
        Integer num39 = num38;
        Integer num40 = num11;
        hashMap.put(num40, sPHINCSPlusParameters66);
        SPHINCSPlusParameters sPHINCSPlusParameters67 = sPHINCSPlusParameters66;
        SPHINCSPlusParameters sPHINCSPlusParameters68 = sPHINCSPlusParameters36;
        Integer num41 = num40;
        Integer num42 = num12;
        hashMap.put(num42, sPHINCSPlusParameters68);
        SPHINCSPlusParameters sPHINCSPlusParameters69 = sPHINCSPlusParameters68;
        SPHINCSPlusParameters sPHINCSPlusParameters70 = sPHINCSPlusParameters38;
        Integer num43 = num42;
        Integer num44 = num13;
        hashMap.put(num44, sPHINCSPlusParameters70);
        SPHINCSPlusParameters sPHINCSPlusParameters71 = sPHINCSPlusParameters70;
        SPHINCSPlusParameters sPHINCSPlusParameters72 = sPHINCSPlusParameters40;
        Integer num45 = num44;
        Integer num46 = num14;
        hashMap.put(num46, sPHINCSPlusParameters72);
        SPHINCSPlusParameters sPHINCSPlusParameters73 = sPHINCSPlusParameters72;
        SPHINCSPlusParameters sPHINCSPlusParameters74 = sPHINCSPlusParameters42;
        Integer num47 = num15;
        Integer num48 = num46;
        Integer num49 = num47;
        hashMap.put(num49, sPHINCSPlusParameters74);
        hashMap2.put(sPHINCSPlusParameters, valueOf);
        hashMap2.put(sPHINCSPlusParameters2, valueOf2);
        hashMap2.put(sPHINCSPlusParameters3, valueOf3);
        hashMap2.put(sPHINCSPlusParameters4, valueOf4);
        hashMap2.put(sPHINCSPlusParameters5, valueOf5);
        hashMap2.put(sPHINCSPlusParameters43, valueOf6);
        hashMap2.put(sPHINCSPlusParameters8, valueOf7);
        hashMap2.put(sPHINCSPlusParameters10, num17);
        hashMap2.put(sPHINCSPlusParameters45, num19);
        hashMap2.put(sPHINCSPlusParameters47, num21);
        hashMap2.put(sPHINCSPlusParameters49, num23);
        hashMap2.put(sPHINCSPlusParameters51, num25);
        hashMap2.put(sPHINCSPlusParameters53, num27);
        hashMap2.put(sPHINCSPlusParameters55, num29);
        hashMap2.put(sPHINCSPlusParameters57, num31);
        hashMap2.put(sPHINCSPlusParameters59, num33);
        hashMap2.put(sPHINCSPlusParameters61, num35);
        hashMap2.put(sPHINCSPlusParameters63, num37);
        hashMap2.put(sPHINCSPlusParameters65, num39);
        hashMap2.put(sPHINCSPlusParameters67, num41);
        hashMap2.put(sPHINCSPlusParameters69, num43);
        hashMap2.put(sPHINCSPlusParameters71, num45);
        hashMap2.put(sPHINCSPlusParameters73, num48);
        hashMap2.put(sPHINCSPlusParameters74, num49);
    }

    private SPHINCSPlusParameters(String str, SPHINCSPlusEngine sPHINCSPlusEngine) {
        this.name = str;
        this.engine = sPHINCSPlusEngine;
    }

    public static Integer getID(SPHINCSPlusParameters sPHINCSPlusParameters) {
        return (Integer) paramsToOid.get(sPHINCSPlusParameters);
    }

    public static SPHINCSPlusParameters getParams(Integer num) {
        return (SPHINCSPlusParameters) oidToParams.get(num);
    }

    public byte[] getEncoded() {
        return Pack.intToBigEndian(getID(this).intValue());
    }

    public SPHINCSPlusEngine getEngine() {
        return this.engine;
    }

    public String getName() {
        return this.name;
    }
}
