package com.google.android.gms.internal.mlkit_vision_face;

import G6.d;
import G6.e;
import G6.f;
import java.io.IOException;

final class zzgi implements e {
    private static final d zzA;
    private static final d zzB;
    private static final d zzC;
    private static final d zzD;
    private static final d zzE;
    private static final d zzF;
    private static final d zzG;
    private static final d zzH;
    private static final d zzI;
    private static final d zzJ;
    private static final d zzK;
    private static final d zzL;
    private static final d zzM;
    private static final d zzN;
    private static final d zzO;
    private static final d zzP;
    private static final d zzQ;
    private static final d zzR;
    private static final d zzS;
    private static final d zzT;
    private static final d zzU;
    private static final d zzV;
    private static final d zzW;
    private static final d zzX;
    private static final d zzY;
    private static final d zzZ;
    static final zzgi zza = new zzgi();
    private static final d zzaa;
    private static final d zzab;
    private static final d zzac;
    private static final d zzad;
    private static final d zzae;
    private static final d zzaf;
    private static final d zzag;
    private static final d zzah;
    private static final d zzai;
    private static final d zzaj;
    private static final d zzak;
    private static final d zzal;
    private static final d zzam;
    private static final d zzan;
    private static final d zzao;
    private static final d zzb;
    private static final d zzc;
    private static final d zzd;
    private static final d zze;
    private static final d zzf;
    private static final d zzg;
    private static final d zzh;
    private static final d zzi;
    private static final d zzj;
    private static final d zzk;
    private static final d zzl;
    private static final d zzm;
    private static final d zzn;
    private static final d zzo;
    private static final d zzp;
    private static final d zzq;
    private static final d zzr;
    private static final d zzs;
    private static final d zzt;
    private static final d zzu;
    private static final d zzv;
    private static final d zzw;
    private static final d zzx;
    private static final d zzy;
    private static final d zzz;

    static {
        d.b a = d.a("systemInfo");
        zzcq zzcq = new zzcq();
        zzcq.zza(1);
        zzb = a.b(zzcq.zzb()).a();
        d.b a2 = d.a("eventName");
        zzcq zzcq2 = new zzcq();
        zzcq2.zza(2);
        zzc = a2.b(zzcq2.zzb()).a();
        d.b a3 = d.a("isThickClient");
        zzcq zzcq3 = new zzcq();
        zzcq3.zza(37);
        zzd = a3.b(zzcq3.zzb()).a();
        d.b a4 = d.a("clientType");
        zzcq zzcq4 = new zzcq();
        zzcq4.zza(61);
        zze = a4.b(zzcq4.zzb()).a();
        d.b a6 = d.a("modelDownloadLogEvent");
        zzcq zzcq5 = new zzcq();
        zzcq5.zza(3);
        zzf = a6.b(zzcq5.zzb()).a();
        d.b a7 = d.a("customModelLoadLogEvent");
        zzcq zzcq6 = new zzcq();
        zzcq6.zza(20);
        zzg = a7.b(zzcq6.zzb()).a();
        d.b a8 = d.a("customModelInferenceLogEvent");
        zzcq zzcq7 = new zzcq();
        zzcq7.zza(4);
        zzh = a8.b(zzcq7.zzb()).a();
        d.b a9 = d.a("customModelCreateLogEvent");
        zzcq zzcq8 = new zzcq();
        zzcq8.zza(29);
        zzi = a9.b(zzcq8.zzb()).a();
        d.b a10 = d.a("onDeviceFaceDetectionLogEvent");
        zzcq zzcq9 = new zzcq();
        zzcq9.zza(5);
        zzj = a10.b(zzcq9.zzb()).a();
        d.b a11 = d.a("onDeviceFaceLoadLogEvent");
        zzcq zzcq10 = new zzcq();
        zzcq10.zza(59);
        zzk = a11.b(zzcq10.zzb()).a();
        d.b a12 = d.a("onDeviceTextDetectionLogEvent");
        zzcq zzcq11 = new zzcq();
        zzcq11.zza(6);
        zzl = a12.b(zzcq11.zzb()).a();
        d.b a13 = d.a("onDeviceBarcodeDetectionLogEvent");
        zzcq zzcq12 = new zzcq();
        zzcq12.zza(7);
        zzm = a13.b(zzcq12.zzb()).a();
        d.b a14 = d.a("onDeviceBarcodeLoadLogEvent");
        zzcq zzcq13 = new zzcq();
        zzcq13.zza(58);
        zzn = a14.b(zzcq13.zzb()).a();
        d.b a15 = d.a("onDeviceImageLabelCreateLogEvent");
        zzcq zzcq14 = new zzcq();
        zzcq14.zza(48);
        zzo = a15.b(zzcq14.zzb()).a();
        d.b a16 = d.a("onDeviceImageLabelLoadLogEvent");
        zzcq zzcq15 = new zzcq();
        zzcq15.zza(49);
        zzp = a16.b(zzcq15.zzb()).a();
        d.b a17 = d.a("onDeviceImageLabelDetectionLogEvent");
        zzcq zzcq16 = new zzcq();
        zzcq16.zza(18);
        zzq = a17.b(zzcq16.zzb()).a();
        d.b a18 = d.a("onDeviceObjectCreateLogEvent");
        zzcq zzcq17 = new zzcq();
        zzcq17.zza(26);
        zzr = a18.b(zzcq17.zzb()).a();
        d.b a19 = d.a("onDeviceObjectLoadLogEvent");
        zzcq zzcq18 = new zzcq();
        zzcq18.zza(27);
        zzs = a19.b(zzcq18.zzb()).a();
        d.b a20 = d.a("onDeviceObjectInferenceLogEvent");
        zzcq zzcq19 = new zzcq();
        zzcq19.zza(28);
        zzt = a20.b(zzcq19.zzb()).a();
        d.b a21 = d.a("onDevicePoseDetectionLogEvent");
        zzcq zzcq20 = new zzcq();
        zzcq20.zza(44);
        zzu = a21.b(zzcq20.zzb()).a();
        d.b a22 = d.a("onDeviceSegmentationLogEvent");
        zzcq zzcq21 = new zzcq();
        zzcq21.zza(45);
        zzv = a22.b(zzcq21.zzb()).a();
        d.b a23 = d.a("onDeviceSmartReplyLogEvent");
        zzcq zzcq22 = new zzcq();
        zzcq22.zza(19);
        zzw = a23.b(zzcq22.zzb()).a();
        d.b a24 = d.a("onDeviceLanguageIdentificationLogEvent");
        zzcq zzcq23 = new zzcq();
        zzcq23.zza(21);
        zzx = a24.b(zzcq23.zzb()).a();
        d.b a25 = d.a("onDeviceTranslationLogEvent");
        zzcq zzcq24 = new zzcq();
        zzcq24.zza(22);
        zzy = a25.b(zzcq24.zzb()).a();
        d.b a26 = d.a("cloudFaceDetectionLogEvent");
        zzcq zzcq25 = new zzcq();
        zzcq25.zza(8);
        zzz = a26.b(zzcq25.zzb()).a();
        d.b a27 = d.a("cloudCropHintDetectionLogEvent");
        zzcq zzcq26 = new zzcq();
        zzcq26.zza(9);
        zzA = a27.b(zzcq26.zzb()).a();
        d.b a28 = d.a("cloudDocumentTextDetectionLogEvent");
        zzcq zzcq27 = new zzcq();
        zzcq27.zza(10);
        zzB = a28.b(zzcq27.zzb()).a();
        d.b a29 = d.a("cloudImagePropertiesDetectionLogEvent");
        zzcq zzcq28 = new zzcq();
        zzcq28.zza(11);
        zzC = a29.b(zzcq28.zzb()).a();
        d.b a30 = d.a("cloudImageLabelDetectionLogEvent");
        zzcq zzcq29 = new zzcq();
        zzcq29.zza(12);
        zzD = a30.b(zzcq29.zzb()).a();
        d.b a31 = d.a("cloudLandmarkDetectionLogEvent");
        zzcq zzcq30 = new zzcq();
        zzcq30.zza(13);
        zzE = a31.b(zzcq30.zzb()).a();
        d.b a32 = d.a("cloudLogoDetectionLogEvent");
        zzcq zzcq31 = new zzcq();
        zzcq31.zza(14);
        zzF = a32.b(zzcq31.zzb()).a();
        d.b a33 = d.a("cloudSafeSearchDetectionLogEvent");
        zzcq zzcq32 = new zzcq();
        zzcq32.zza(15);
        zzG = a33.b(zzcq32.zzb()).a();
        d.b a34 = d.a("cloudTextDetectionLogEvent");
        zzcq zzcq33 = new zzcq();
        zzcq33.zza(16);
        zzH = a34.b(zzcq33.zzb()).a();
        d.b a35 = d.a("cloudWebSearchDetectionLogEvent");
        zzcq zzcq34 = new zzcq();
        zzcq34.zza(17);
        zzI = a35.b(zzcq34.zzb()).a();
        d.b a36 = d.a("automlImageLabelingCreateLogEvent");
        zzcq zzcq35 = new zzcq();
        zzcq35.zza(23);
        zzJ = a36.b(zzcq35.zzb()).a();
        d.b a37 = d.a("automlImageLabelingLoadLogEvent");
        zzcq zzcq36 = new zzcq();
        zzcq36.zza(24);
        zzK = a37.b(zzcq36.zzb()).a();
        d.b a38 = d.a("automlImageLabelingInferenceLogEvent");
        zzcq zzcq37 = new zzcq();
        zzcq37.zza(25);
        zzL = a38.b(zzcq37.zzb()).a();
        d.b a39 = d.a("isModelDownloadedLogEvent");
        zzcq zzcq38 = new zzcq();
        zzcq38.zza(39);
        zzM = a39.b(zzcq38.zzb()).a();
        d.b a40 = d.a("deleteModelLogEvent");
        zzcq zzcq39 = new zzcq();
        zzcq39.zza(40);
        zzN = a40.b(zzcq39.zzb()).a();
        d.b a41 = d.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcq zzcq40 = new zzcq();
        zzcq40.zza(30);
        zzO = a41.b(zzcq40.zzb()).a();
        d.b a42 = d.a("aggregatedCustomModelInferenceLogEvent");
        zzcq zzcq41 = new zzcq();
        zzcq41.zza(31);
        zzP = a42.b(zzcq41.zzb()).a();
        d.b a43 = d.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcq zzcq42 = new zzcq();
        zzcq42.zza(32);
        zzQ = a43.b(zzcq42.zzb()).a();
        d.b a44 = d.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcq zzcq43 = new zzcq();
        zzcq43.zza(33);
        zzR = a44.b(zzcq43.zzb()).a();
        d.b a45 = d.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcq zzcq44 = new zzcq();
        zzcq44.zza(34);
        zzS = a45.b(zzcq44.zzb()).a();
        d.b a46 = d.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcq zzcq45 = new zzcq();
        zzcq45.zza(35);
        zzT = a46.b(zzcq45.zzb()).a();
        d.b a47 = d.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzcq zzcq46 = new zzcq();
        zzcq46.zza(36);
        zzU = a47.b(zzcq46.zzb()).a();
        d.b a48 = d.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzcq zzcq47 = new zzcq();
        zzcq47.zza(46);
        zzV = a48.b(zzcq47.zzb()).a();
        d.b a49 = d.a("aggregatedOnDeviceSegmentationLogEvent");
        zzcq zzcq48 = new zzcq();
        zzcq48.zza(47);
        zzW = a49.b(zzcq48.zzb()).a();
        d.b a50 = d.a("pipelineAccelerationInferenceEvents");
        zzcq zzcq49 = new zzcq();
        zzcq49.zza(69);
        zzX = a50.b(zzcq49.zzb()).a();
        d.b a51 = d.a("remoteConfigLogEvent");
        zzcq zzcq50 = new zzcq();
        zzcq50.zza(42);
        zzY = a51.b(zzcq50.zzb()).a();
        d.b a52 = d.a("inputImageConstructionLogEvent");
        zzcq zzcq51 = new zzcq();
        zzcq51.zza(50);
        zzZ = a52.b(zzcq51.zzb()).a();
        d.b a53 = d.a("leakedHandleEvent");
        zzcq zzcq52 = new zzcq();
        zzcq52.zza(51);
        zzaa = a53.b(zzcq52.zzb()).a();
        d.b a54 = d.a("cameraSourceLogEvent");
        zzcq zzcq53 = new zzcq();
        zzcq53.zza(52);
        zzab = a54.b(zzcq53.zzb()).a();
        d.b a55 = d.a("imageLabelOptionalModuleLogEvent");
        zzcq zzcq54 = new zzcq();
        zzcq54.zza(53);
        zzac = a55.b(zzcq54.zzb()).a();
        d.b a56 = d.a("languageIdentificationOptionalModuleLogEvent");
        zzcq zzcq55 = new zzcq();
        zzcq55.zza(54);
        zzad = a56.b(zzcq55.zzb()).a();
        d.b a57 = d.a("faceDetectionOptionalModuleLogEvent");
        zzcq zzcq56 = new zzcq();
        zzcq56.zza(60);
        zzae = a57.b(zzcq56.zzb()).a();
        d.b a58 = d.a("nlClassifierOptionalModuleLogEvent");
        zzcq zzcq57 = new zzcq();
        zzcq57.zza(55);
        zzaf = a58.b(zzcq57.zzb()).a();
        d.b a59 = d.a("nlClassifierClientLibraryLogEvent");
        zzcq zzcq58 = new zzcq();
        zzcq58.zza(56);
        zzag = a59.b(zzcq58.zzb()).a();
        d.b a60 = d.a("accelerationAllowlistLogEvent");
        zzcq zzcq59 = new zzcq();
        zzcq59.zza(57);
        zzah = a60.b(zzcq59.zzb()).a();
        d.b a61 = d.a("toxicityDetectionCreateEvent");
        zzcq zzcq60 = new zzcq();
        zzcq60.zza(62);
        zzai = a61.b(zzcq60.zzb()).a();
        d.b a62 = d.a("toxicityDetectionLoadEvent");
        zzcq zzcq61 = new zzcq();
        zzcq61.zza(63);
        zzaj = a62.b(zzcq61.zzb()).a();
        d.b a63 = d.a("toxicityDetectionInferenceEvent");
        zzcq zzcq62 = new zzcq();
        zzcq62.zza(64);
        zzak = a63.b(zzcq62.zzb()).a();
        d.b a64 = d.a("barcodeDetectionOptionalModuleLogEvent");
        zzcq zzcq63 = new zzcq();
        zzcq63.zza(65);
        zzal = a64.b(zzcq63.zzb()).a();
        d.b a65 = d.a("customImageLabelOptionalModuleLogEvent");
        zzcq zzcq64 = new zzcq();
        zzcq64.zza(66);
        zzam = a65.b(zzcq64.zzb()).a();
        d.b a66 = d.a("codeScannerScanApiEvent");
        zzcq zzcq65 = new zzcq();
        zzcq65.zza(67);
        zzan = a66.b(zzcq65.zzb()).a();
        d.b a67 = d.a("codeScannerOptionalModuleEvent");
        zzcq zzcq66 = new zzcq();
        zzcq66.zza(68);
        zzao = a67.b(zzcq66.zzb()).a();
    }

    private zzgi() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzke zzke = (zzke) obj;
        f fVar = (f) obj2;
        fVar.add(zzb, zzke.zzf());
        fVar.add(zzc, zzke.zzc());
        fVar.add(zzd, (Object) null);
        fVar.add(zze, zzke.zzb());
        fVar.add(zzf, (Object) null);
        fVar.add(zzg, (Object) null);
        fVar.add(zzh, (Object) null);
        fVar.add(zzi, (Object) null);
        fVar.add(zzj, zzke.zzd());
        fVar.add(zzk, zzke.zze());
        fVar.add(zzl, (Object) null);
        fVar.add(zzm, (Object) null);
        fVar.add(zzn, (Object) null);
        fVar.add(zzo, (Object) null);
        fVar.add(zzp, (Object) null);
        fVar.add(zzq, (Object) null);
        fVar.add(zzr, (Object) null);
        fVar.add(zzs, (Object) null);
        fVar.add(zzt, (Object) null);
        fVar.add(zzu, (Object) null);
        fVar.add(zzv, (Object) null);
        fVar.add(zzw, (Object) null);
        fVar.add(zzx, (Object) null);
        fVar.add(zzy, (Object) null);
        fVar.add(zzz, (Object) null);
        fVar.add(zzA, (Object) null);
        fVar.add(zzB, (Object) null);
        fVar.add(zzC, (Object) null);
        fVar.add(zzD, (Object) null);
        fVar.add(zzE, (Object) null);
        fVar.add(zzF, (Object) null);
        fVar.add(zzG, (Object) null);
        fVar.add(zzH, (Object) null);
        fVar.add(zzI, (Object) null);
        fVar.add(zzJ, (Object) null);
        fVar.add(zzK, (Object) null);
        fVar.add(zzL, (Object) null);
        fVar.add(zzM, (Object) null);
        fVar.add(zzN, (Object) null);
        fVar.add(zzO, (Object) null);
        fVar.add(zzP, (Object) null);
        fVar.add(zzQ, zzke.zza());
        fVar.add(zzR, (Object) null);
        fVar.add(zzS, (Object) null);
        fVar.add(zzT, (Object) null);
        fVar.add(zzU, (Object) null);
        fVar.add(zzV, (Object) null);
        fVar.add(zzW, (Object) null);
        fVar.add(zzX, (Object) null);
        fVar.add(zzY, (Object) null);
        fVar.add(zzZ, (Object) null);
        fVar.add(zzaa, (Object) null);
        fVar.add(zzab, (Object) null);
        fVar.add(zzac, (Object) null);
        fVar.add(zzad, (Object) null);
        fVar.add(zzae, (Object) null);
        fVar.add(zzaf, (Object) null);
        fVar.add(zzag, (Object) null);
        fVar.add(zzah, (Object) null);
        fVar.add(zzai, (Object) null);
        fVar.add(zzaj, (Object) null);
        fVar.add(zzak, (Object) null);
        fVar.add(zzal, (Object) null);
        fVar.add(zzam, (Object) null);
        fVar.add(zzan, (Object) null);
        fVar.add(zzao, (Object) null);
    }
}
