package com.google.android.gms.internal.mlkit_vision_common;

import G6.d;
import G6.e;
import G6.f;
import java.io.IOException;

final class zzeo implements e {
    private static final d zzA;
    private static final d zzB;
    private static final d zzC;
    private static final d zzD;
    private static final d zzE;
    private static final d zzF;
    private static final d zzG;
    private static final d zzH;
    private static final d zzI;
    private static final d zzJ;
    private static final d zzK;
    private static final d zzL;
    private static final d zzM;
    private static final d zzN;
    private static final d zzO;
    private static final d zzP;
    private static final d zzQ;
    private static final d zzR;
    private static final d zzS;
    private static final d zzT;
    private static final d zzU;
    private static final d zzV;
    private static final d zzW;
    private static final d zzX;
    private static final d zzY;
    private static final d zzZ;
    static final zzeo zza = new zzeo();
    private static final d zzaA;
    private static final d zzaB;
    private static final d zzaC;
    private static final d zzaD;
    private static final d zzaE;
    private static final d zzaF;
    private static final d zzaG;
    private static final d zzaH;
    private static final d zzaI;
    private static final d zzaJ;
    private static final d zzaK;
    private static final d zzaL;
    private static final d zzaM;
    private static final d zzaa;
    private static final d zzab;
    private static final d zzac;
    private static final d zzad;
    private static final d zzae;
    private static final d zzaf;
    private static final d zzag;
    private static final d zzah;
    private static final d zzai;
    private static final d zzaj;
    private static final d zzak;
    private static final d zzal;
    private static final d zzam;
    private static final d zzan;
    private static final d zzao;
    private static final d zzap;
    private static final d zzaq;
    private static final d zzar;
    private static final d zzas;
    private static final d zzat;
    private static final d zzau;
    private static final d zzav;
    private static final d zzaw;
    private static final d zzax;
    private static final d zzay;
    private static final d zzaz;
    private static final d zzb;
    private static final d zzc;
    private static final d zzd;
    private static final d zze;
    private static final d zzf;
    private static final d zzg;
    private static final d zzh;
    private static final d zzi;
    private static final d zzj;
    private static final d zzk;
    private static final d zzl;
    private static final d zzm;
    private static final d zzn;
    private static final d zzo;
    private static final d zzp;
    private static final d zzq;
    private static final d zzr;
    private static final d zzs;
    private static final d zzt;
    private static final d zzu;
    private static final d zzv;
    private static final d zzw;
    private static final d zzx;
    private static final d zzy;
    private static final d zzz;

    static {
        d.b a = d.a("systemInfo");
        zzae zzae2 = new zzae();
        zzae2.zza(1);
        zzb = a.b(zzae2.zzb()).a();
        d.b a2 = d.a("eventName");
        zzae zzae3 = new zzae();
        zzae3.zza(2);
        zzc = a2.b(zzae3.zzb()).a();
        d.b a3 = d.a("isThickClient");
        zzae zzae4 = new zzae();
        zzae4.zza(37);
        zzd = a3.b(zzae4.zzb()).a();
        d.b a4 = d.a("clientType");
        zzae zzae5 = new zzae();
        zzae5.zza(61);
        zze = a4.b(zzae5.zzb()).a();
        d.b a6 = d.a("modelDownloadLogEvent");
        zzae zzae6 = new zzae();
        zzae6.zza(3);
        zzf = a6.b(zzae6.zzb()).a();
        d.b a7 = d.a("customModelLoadLogEvent");
        zzae zzae7 = new zzae();
        zzae7.zza(20);
        zzg = a7.b(zzae7.zzb()).a();
        d.b a8 = d.a("customModelInferenceLogEvent");
        zzae zzae8 = new zzae();
        zzae8.zza(4);
        zzh = a8.b(zzae8.zzb()).a();
        d.b a9 = d.a("customModelCreateLogEvent");
        zzae zzae9 = new zzae();
        zzae9.zza(29);
        zzi = a9.b(zzae9.zzb()).a();
        d.b a10 = d.a("onDeviceFaceDetectionLogEvent");
        zzae zzae10 = new zzae();
        zzae10.zza(5);
        zzj = a10.b(zzae10.zzb()).a();
        d.b a11 = d.a("onDeviceFaceLoadLogEvent");
        zzae zzae11 = new zzae();
        zzae11.zza(59);
        zzk = a11.b(zzae11.zzb()).a();
        d.b a12 = d.a("onDeviceTextDetectionLogEvent");
        zzae zzae12 = new zzae();
        zzae12.zza(6);
        zzl = a12.b(zzae12.zzb()).a();
        d.b a13 = d.a("onDeviceTextDetectionLoadLogEvent");
        zzae zzae13 = new zzae();
        zzae13.zza(79);
        zzm = a13.b(zzae13.zzb()).a();
        d.b a14 = d.a("onDeviceBarcodeDetectionLogEvent");
        zzae zzae14 = new zzae();
        zzae14.zza(7);
        zzn = a14.b(zzae14.zzb()).a();
        d.b a15 = d.a("onDeviceBarcodeLoadLogEvent");
        zzae zzae15 = new zzae();
        zzae15.zza(58);
        zzo = a15.b(zzae15.zzb()).a();
        d.b a16 = d.a("onDeviceImageLabelCreateLogEvent");
        zzae zzae16 = new zzae();
        zzae16.zza(48);
        zzp = a16.b(zzae16.zzb()).a();
        d.b a17 = d.a("onDeviceImageLabelLoadLogEvent");
        zzae zzae17 = new zzae();
        zzae17.zza(49);
        zzq = a17.b(zzae17.zzb()).a();
        d.b a18 = d.a("onDeviceImageLabelDetectionLogEvent");
        zzae zzae18 = new zzae();
        zzae18.zza(18);
        zzr = a18.b(zzae18.zzb()).a();
        d.b a19 = d.a("onDeviceObjectCreateLogEvent");
        zzae zzae19 = new zzae();
        zzae19.zza(26);
        zzs = a19.b(zzae19.zzb()).a();
        d.b a20 = d.a("onDeviceObjectLoadLogEvent");
        zzae zzae20 = new zzae();
        zzae20.zza(27);
        zzt = a20.b(zzae20.zzb()).a();
        d.b a21 = d.a("onDeviceObjectInferenceLogEvent");
        zzae zzae21 = new zzae();
        zzae21.zza(28);
        zzu = a21.b(zzae21.zzb()).a();
        d.b a22 = d.a("onDevicePoseDetectionLogEvent");
        zzae zzae22 = new zzae();
        zzae22.zza(44);
        zzv = a22.b(zzae22.zzb()).a();
        d.b a23 = d.a("onDeviceSegmentationLogEvent");
        zzae zzae23 = new zzae();
        zzae23.zza(45);
        zzw = a23.b(zzae23.zzb()).a();
        d.b a24 = d.a("onDeviceSmartReplyLogEvent");
        zzae zzae24 = new zzae();
        zzae24.zza(19);
        zzx = a24.b(zzae24.zzb()).a();
        d.b a25 = d.a("onDeviceLanguageIdentificationLogEvent");
        zzae zzae25 = new zzae();
        zzae25.zza(21);
        zzy = a25.b(zzae25.zzb()).a();
        d.b a26 = d.a("onDeviceTranslationLogEvent");
        zzae zzae26 = new zzae();
        zzae26.zza(22);
        zzz = a26.b(zzae26.zzb()).a();
        d.b a27 = d.a("cloudFaceDetectionLogEvent");
        zzae zzae27 = new zzae();
        zzae27.zza(8);
        zzA = a27.b(zzae27.zzb()).a();
        d.b a28 = d.a("cloudCropHintDetectionLogEvent");
        zzae zzae28 = new zzae();
        zzae28.zza(9);
        zzB = a28.b(zzae28.zzb()).a();
        d.b a29 = d.a("cloudDocumentTextDetectionLogEvent");
        zzae zzae29 = new zzae();
        zzae29.zza(10);
        zzC = a29.b(zzae29.zzb()).a();
        d.b a30 = d.a("cloudImagePropertiesDetectionLogEvent");
        zzae zzae30 = new zzae();
        zzae30.zza(11);
        zzD = a30.b(zzae30.zzb()).a();
        d.b a31 = d.a("cloudImageLabelDetectionLogEvent");
        zzae zzae31 = new zzae();
        zzae31.zza(12);
        zzE = a31.b(zzae31.zzb()).a();
        d.b a32 = d.a("cloudLandmarkDetectionLogEvent");
        zzae zzae32 = new zzae();
        zzae32.zza(13);
        zzF = a32.b(zzae32.zzb()).a();
        d.b a33 = d.a("cloudLogoDetectionLogEvent");
        zzae zzae33 = new zzae();
        zzae33.zza(14);
        zzG = a33.b(zzae33.zzb()).a();
        d.b a34 = d.a("cloudSafeSearchDetectionLogEvent");
        zzae zzae34 = new zzae();
        zzae34.zza(15);
        zzH = a34.b(zzae34.zzb()).a();
        d.b a35 = d.a("cloudTextDetectionLogEvent");
        zzae zzae35 = new zzae();
        zzae35.zza(16);
        zzI = a35.b(zzae35.zzb()).a();
        d.b a36 = d.a("cloudWebSearchDetectionLogEvent");
        zzae zzae36 = new zzae();
        zzae36.zza(17);
        zzJ = a36.b(zzae36.zzb()).a();
        d.b a37 = d.a("automlImageLabelingCreateLogEvent");
        zzae zzae37 = new zzae();
        zzae37.zza(23);
        zzK = a37.b(zzae37.zzb()).a();
        d.b a38 = d.a("automlImageLabelingLoadLogEvent");
        zzae zzae38 = new zzae();
        zzae38.zza(24);
        zzL = a38.b(zzae38.zzb()).a();
        d.b a39 = d.a("automlImageLabelingInferenceLogEvent");
        zzae zzae39 = new zzae();
        zzae39.zza(25);
        zzM = a39.b(zzae39.zzb()).a();
        d.b a40 = d.a("isModelDownloadedLogEvent");
        zzae zzae40 = new zzae();
        zzae40.zza(39);
        zzN = a40.b(zzae40.zzb()).a();
        d.b a41 = d.a("deleteModelLogEvent");
        zzae zzae41 = new zzae();
        zzae41.zza(40);
        zzO = a41.b(zzae41.zzb()).a();
        d.b a42 = d.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzae zzae42 = new zzae();
        zzae42.zza(30);
        zzP = a42.b(zzae42.zzb()).a();
        d.b a43 = d.a("aggregatedCustomModelInferenceLogEvent");
        zzae zzae43 = new zzae();
        zzae43.zza(31);
        zzQ = a43.b(zzae43.zzb()).a();
        d.b a44 = d.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzae zzae44 = new zzae();
        zzae44.zza(32);
        zzR = a44.b(zzae44.zzb()).a();
        d.b a45 = d.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzae zzae45 = new zzae();
        zzae45.zza(33);
        zzS = a45.b(zzae45.zzb()).a();
        d.b a46 = d.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzae zzae46 = new zzae();
        zzae46.zza(34);
        zzT = a46.b(zzae46.zzb()).a();
        d.b a47 = d.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzae zzae47 = new zzae();
        zzae47.zza(35);
        zzU = a47.b(zzae47.zzb()).a();
        d.b a48 = d.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzae zzae48 = new zzae();
        zzae48.zza(36);
        zzV = a48.b(zzae48.zzb()).a();
        d.b a49 = d.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzae zzae49 = new zzae();
        zzae49.zza(46);
        zzW = a49.b(zzae49.zzb()).a();
        d.b a50 = d.a("aggregatedOnDeviceSegmentationLogEvent");
        zzae zzae50 = new zzae();
        zzae50.zza(47);
        zzX = a50.b(zzae50.zzb()).a();
        d.b a51 = d.a("pipelineAccelerationInferenceEvents");
        zzae zzae51 = new zzae();
        zzae51.zza(69);
        zzY = a51.b(zzae51.zzb()).a();
        d.b a52 = d.a("remoteConfigLogEvent");
        zzae zzae52 = new zzae();
        zzae52.zza(42);
        zzZ = a52.b(zzae52.zzb()).a();
        d.b a53 = d.a("inputImageConstructionLogEvent");
        zzae zzae53 = new zzae();
        zzae53.zza(50);
        zzaa = a53.b(zzae53.zzb()).a();
        d.b a54 = d.a("leakedHandleEvent");
        zzae zzae54 = new zzae();
        zzae54.zza(51);
        zzab = a54.b(zzae54.zzb()).a();
        d.b a55 = d.a("cameraSourceLogEvent");
        zzae zzae55 = new zzae();
        zzae55.zza(52);
        zzac = a55.b(zzae55.zzb()).a();
        d.b a56 = d.a("imageLabelOptionalModuleLogEvent");
        zzae zzae56 = new zzae();
        zzae56.zza(53);
        zzad = a56.b(zzae56.zzb()).a();
        d.b a57 = d.a("languageIdentificationOptionalModuleLogEvent");
        zzae zzae57 = new zzae();
        zzae57.zza(54);
        zzae = a57.b(zzae57.zzb()).a();
        d.b a58 = d.a("faceDetectionOptionalModuleLogEvent");
        zzae zzae58 = new zzae();
        zzae58.zza(60);
        zzaf = a58.b(zzae58.zzb()).a();
        d.b a59 = d.a("documentDetectionOptionalModuleLogEvent");
        zzae zzae59 = new zzae();
        zzae59.zza(85);
        zzag = a59.b(zzae59.zzb()).a();
        d.b a60 = d.a("documentCroppingOptionalModuleLogEvent");
        zzae zzae60 = new zzae();
        zzae60.zza(86);
        zzah = a60.b(zzae60.zzb()).a();
        d.b a61 = d.a("documentEnhancementOptionalModuleLogEvent");
        zzae zzae61 = new zzae();
        zzae61.zza(87);
        zzai = a61.b(zzae61.zzb()).a();
        d.b a62 = d.a("nlClassifierOptionalModuleLogEvent");
        zzae zzae62 = new zzae();
        zzae62.zza(55);
        zzaj = a62.b(zzae62.zzb()).a();
        d.b a63 = d.a("nlClassifierClientLibraryLogEvent");
        zzae zzae63 = new zzae();
        zzae63.zza(56);
        zzak = a63.b(zzae63.zzb()).a();
        d.b a64 = d.a("accelerationAllowlistLogEvent");
        zzae zzae64 = new zzae();
        zzae64.zza(57);
        zzal = a64.b(zzae64.zzb()).a();
        d.b a65 = d.a("toxicityDetectionCreateEvent");
        zzae zzae65 = new zzae();
        zzae65.zza(62);
        zzam = a65.b(zzae65.zzb()).a();
        d.b a66 = d.a("toxicityDetectionLoadEvent");
        zzae zzae66 = new zzae();
        zzae66.zza(63);
        zzan = a66.b(zzae66.zzb()).a();
        d.b a67 = d.a("toxicityDetectionInferenceEvent");
        zzae zzae67 = new zzae();
        zzae67.zza(64);
        zzao = a67.b(zzae67.zzb()).a();
        d.b a68 = d.a("barcodeDetectionOptionalModuleLogEvent");
        zzae zzae68 = new zzae();
        zzae68.zza(65);
        zzap = a68.b(zzae68.zzb()).a();
        d.b a69 = d.a("customImageLabelOptionalModuleLogEvent");
        zzae zzae69 = new zzae();
        zzae69.zza(66);
        zzaq = a69.b(zzae69.zzb()).a();
        d.b a70 = d.a("codeScannerScanApiEvent");
        zzae zzae70 = new zzae();
        zzae70.zza(67);
        zzar = a70.b(zzae70.zzb()).a();
        d.b a71 = d.a("codeScannerOptionalModuleEvent");
        zzae zzae71 = new zzae();
        zzae71.zza(68);
        zzas = a71.b(zzae71.zzb()).a();
        d.b a72 = d.a("onDeviceExplicitContentCreateLogEvent");
        zzae zzae72 = new zzae();
        zzae72.zza(70);
        zzat = a72.b(zzae72.zzb()).a();
        d.b a73 = d.a("onDeviceExplicitContentLoadLogEvent");
        zzae zzae73 = new zzae();
        zzae73.zza(71);
        zzau = a73.b(zzae73.zzb()).a();
        d.b a74 = d.a("onDeviceExplicitContentInferenceLogEvent");
        zzae zzae74 = new zzae();
        zzae74.zza(72);
        zzav = a74.b(zzae74.zzb()).a();
        d.b a75 = d.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzae zzae75 = new zzae();
        zzae75.zza(73);
        zzaw = a75.b(zzae75.zzb()).a();
        d.b a76 = d.a("onDeviceFaceMeshCreateLogEvent");
        zzae zzae76 = new zzae();
        zzae76.zza(74);
        zzax = a76.b(zzae76.zzb()).a();
        d.b a77 = d.a("onDeviceFaceMeshLoadLogEvent");
        zzae zzae77 = new zzae();
        zzae77.zza(75);
        zzay = a77.b(zzae77.zzb()).a();
        d.b a78 = d.a("onDeviceFaceMeshLogEvent");
        zzae zzae78 = new zzae();
        zzae78.zza(76);
        zzaz = a78.b(zzae78.zzb()).a();
        d.b a79 = d.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzae zzae79 = new zzae();
        zzae79.zza(77);
        zzaA = a79.b(zzae79.zzb()).a();
        d.b a80 = d.a("smartReplyOptionalModuleLogEvent");
        zzae zzae80 = new zzae();
        zzae80.zza(78);
        zzaB = a80.b(zzae80.zzb()).a();
        d.b a81 = d.a("textDetectionOptionalModuleLogEvent");
        zzae zzae81 = new zzae();
        zzae81.zza(80);
        zzaC = a81.b(zzae81.zzb()).a();
        d.b a82 = d.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzae zzae82 = new zzae();
        zzae82.zza(81);
        zzaD = a82.b(zzae82.zzb()).a();
        d.b a83 = d.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzae zzae83 = new zzae();
        zzae83.zza(82);
        zzaE = a83.b(zzae83.zzb()).a();
        d.b a84 = d.a("onDeviceImageQualityAnalysisLogEvent");
        zzae zzae84 = new zzae();
        zzae84.zza(83);
        zzaF = a84.b(zzae84.zzb()).a();
        d.b a85 = d.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzae zzae85 = new zzae();
        zzae85.zza(84);
        zzaG = a85.b(zzae85.zzb()).a();
        d.b a86 = d.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzae zzae86 = new zzae();
        zzae86.zza(88);
        zzaH = a86.b(zzae86.zzb()).a();
        d.b a87 = d.a("imageCaptioningOptionalModuleLogEvent");
        zzae zzae87 = new zzae();
        zzae87.zza(89);
        zzaI = a87.b(zzae87.zzb()).a();
        d.b a88 = d.a("onDeviceImageCaptioningCreateLogEvent");
        zzae zzae88 = new zzae();
        zzae88.zza(90);
        zzaJ = a88.b(zzae88.zzb()).a();
        d.b a89 = d.a("onDeviceImageCaptioningLoadLogEvent");
        zzae zzae89 = new zzae();
        zzae89.zza(91);
        zzaK = a89.b(zzae89.zzb()).a();
        d.b a90 = d.a("onDeviceImageCaptioningInferenceLogEvent");
        zzae zzae90 = new zzae();
        zzae90.zza(92);
        zzaL = a90.b(zzae90.zzb()).a();
        d.b a91 = d.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzae zzae91 = new zzae();
        zzae91.zza(93);
        zzaM = a91.b(zzae91.zzb()).a();
    }

    private zzeo() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zziy zziy = (zziy) obj;
        f fVar = (f) obj2;
        fVar.add(zzb, zziy.zzc());
        fVar.add(zzc, zziy.zzb());
        fVar.add(zzd, (Object) null);
        fVar.add(zze, (Object) null);
        fVar.add(zzf, (Object) null);
        fVar.add(zzg, (Object) null);
        fVar.add(zzh, (Object) null);
        fVar.add(zzi, (Object) null);
        fVar.add(zzj, (Object) null);
        fVar.add(zzk, (Object) null);
        fVar.add(zzl, (Object) null);
        fVar.add(zzm, (Object) null);
        fVar.add(zzn, (Object) null);
        fVar.add(zzo, (Object) null);
        fVar.add(zzp, (Object) null);
        fVar.add(zzq, (Object) null);
        fVar.add(zzr, (Object) null);
        fVar.add(zzs, (Object) null);
        fVar.add(zzt, (Object) null);
        fVar.add(zzu, (Object) null);
        fVar.add(zzv, (Object) null);
        fVar.add(zzw, (Object) null);
        fVar.add(zzx, (Object) null);
        fVar.add(zzy, (Object) null);
        fVar.add(zzz, (Object) null);
        fVar.add(zzA, (Object) null);
        fVar.add(zzB, (Object) null);
        fVar.add(zzC, (Object) null);
        fVar.add(zzD, (Object) null);
        fVar.add(zzE, (Object) null);
        fVar.add(zzF, (Object) null);
        fVar.add(zzG, (Object) null);
        fVar.add(zzH, (Object) null);
        fVar.add(zzI, (Object) null);
        fVar.add(zzJ, (Object) null);
        fVar.add(zzK, (Object) null);
        fVar.add(zzL, (Object) null);
        fVar.add(zzM, (Object) null);
        fVar.add(zzN, (Object) null);
        fVar.add(zzO, (Object) null);
        fVar.add(zzP, (Object) null);
        fVar.add(zzQ, (Object) null);
        fVar.add(zzR, (Object) null);
        fVar.add(zzS, (Object) null);
        fVar.add(zzT, (Object) null);
        fVar.add(zzU, (Object) null);
        fVar.add(zzV, (Object) null);
        fVar.add(zzW, (Object) null);
        fVar.add(zzX, (Object) null);
        fVar.add(zzY, (Object) null);
        fVar.add(zzZ, (Object) null);
        fVar.add(zzaa, zziy.zza());
        fVar.add(zzab, (Object) null);
        fVar.add(zzac, (Object) null);
        fVar.add(zzad, (Object) null);
        fVar.add(zzae, (Object) null);
        fVar.add(zzaf, (Object) null);
        fVar.add(zzag, (Object) null);
        fVar.add(zzah, (Object) null);
        fVar.add(zzai, (Object) null);
        fVar.add(zzaj, (Object) null);
        fVar.add(zzak, (Object) null);
        fVar.add(zzal, (Object) null);
        fVar.add(zzam, (Object) null);
        fVar.add(zzan, (Object) null);
        fVar.add(zzao, (Object) null);
        fVar.add(zzap, (Object) null);
        fVar.add(zzaq, (Object) null);
        fVar.add(zzar, (Object) null);
        fVar.add(zzas, (Object) null);
        fVar.add(zzat, (Object) null);
        fVar.add(zzau, (Object) null);
        fVar.add(zzav, (Object) null);
        fVar.add(zzaw, (Object) null);
        fVar.add(zzax, (Object) null);
        fVar.add(zzay, (Object) null);
        fVar.add(zzaz, (Object) null);
        fVar.add(zzaA, (Object) null);
        fVar.add(zzaB, (Object) null);
        fVar.add(zzaC, (Object) null);
        fVar.add(zzaD, (Object) null);
        fVar.add(zzaE, (Object) null);
        fVar.add(zzaF, (Object) null);
        fVar.add(zzaG, (Object) null);
        fVar.add(zzaH, (Object) null);
        fVar.add(zzaI, (Object) null);
        fVar.add(zzaJ, (Object) null);
        fVar.add(zzaK, (Object) null);
        fVar.add(zzaL, (Object) null);
        fVar.add(zzaM, (Object) null);
    }
}
