package com.google.android.gms.internal.mlkit_vision_barcode;

import G6.d;
import G6.e;
import G6.f;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.eac.CertificateBody;
import com.fis.ekyc.nfc.build_in.eidparser.cbeff.ISO781611;
import com.fis.ekyc.nfc.build_in.eidparser.lds.LDSFile;
import java.io.IOException;

final class zzkv implements e {
    private static final d zzA;
    private static final d zzB;
    private static final d zzC;
    private static final d zzD;
    private static final d zzE;
    private static final d zzF;
    private static final d zzG;
    private static final d zzH;
    private static final d zzI;
    private static final d zzJ;
    private static final d zzK;
    private static final d zzL;
    private static final d zzM;
    private static final d zzN;
    private static final d zzO;
    private static final d zzP;
    private static final d zzQ;
    private static final d zzR;
    private static final d zzS;
    private static final d zzT;
    private static final d zzU;
    private static final d zzV;
    private static final d zzW;
    private static final d zzX;
    private static final d zzY;
    private static final d zzZ;
    static final zzkv zza = new zzkv();
    private static final d zzaA;
    private static final d zzaB;
    private static final d zzaC;
    private static final d zzaD;
    private static final d zzaE;
    private static final d zzaF;
    private static final d zzaG;
    private static final d zzaH;
    private static final d zzaI;
    private static final d zzaJ;
    private static final d zzaK;
    private static final d zzaL;
    private static final d zzaM;
    private static final d zzaN;
    private static final d zzaO;
    private static final d zzaP;
    private static final d zzaQ;
    private static final d zzaR;
    private static final d zzaS;
    private static final d zzaT;
    private static final d zzaU;
    private static final d zzaV;
    private static final d zzaW;
    private static final d zzaX;
    private static final d zzaY;
    private static final d zzaZ;
    private static final d zzaa;
    private static final d zzab;
    private static final d zzac;
    private static final d zzad;
    private static final d zzae;
    private static final d zzaf;
    private static final d zzag;
    private static final d zzah;
    private static final d zzai;
    private static final d zzaj;
    private static final d zzak;
    private static final d zzal;
    private static final d zzam;
    private static final d zzan;
    private static final d zzao;
    private static final d zzap;
    private static final d zzaq;
    private static final d zzar;
    private static final d zzas;
    private static final d zzat;
    private static final d zzau;
    private static final d zzav;
    private static final d zzaw;
    private static final d zzax;
    private static final d zzay;
    private static final d zzaz;
    private static final d zzb;
    private static final d zzba;
    private static final d zzbb;
    private static final d zzbc;
    private static final d zzbd;
    private static final d zzbe;
    private static final d zzbf;
    private static final d zzbg;
    private static final d zzbh;
    private static final d zzbi;
    private static final d zzbj;
    private static final d zzbk;
    private static final d zzbl;
    private static final d zzbm;
    private static final d zzbn;
    private static final d zzbo;
    private static final d zzbp;
    private static final d zzbq;
    private static final d zzbr;
    private static final d zzbs;
    private static final d zzbt;
    private static final d zzbu;
    private static final d zzbv;
    private static final d zzbw;
    private static final d zzbx;
    private static final d zzby;
    private static final d zzc;
    private static final d zzd;
    private static final d zze;
    private static final d zzf;
    private static final d zzg;
    private static final d zzh;
    private static final d zzi;
    private static final d zzj;
    private static final d zzk;
    private static final d zzl;
    private static final d zzm;
    private static final d zzn;
    private static final d zzo;
    private static final d zzp;
    private static final d zzq;
    private static final d zzr;
    private static final d zzs;
    private static final d zzt;
    private static final d zzu;
    private static final d zzv;
    private static final d zzw;
    private static final d zzx;
    private static final d zzy;
    private static final d zzz;

    static {
        d.b a = d.a("systemInfo");
        zzfa zzfa = new zzfa();
        zzfa.zza(1);
        zzb = a.b(zzfa.zzb()).a();
        d.b a2 = d.a("eventName");
        zzfa zzfa2 = new zzfa();
        zzfa2.zza(2);
        zzc = a2.b(zzfa2.zzb()).a();
        d.b a3 = d.a("isThickClient");
        zzfa zzfa3 = new zzfa();
        zzfa3.zza(37);
        zzd = a3.b(zzfa3.zzb()).a();
        d.b a4 = d.a("clientType");
        zzfa zzfa4 = new zzfa();
        zzfa4.zza(61);
        zze = a4.b(zzfa4.zzb()).a();
        d.b a6 = d.a("modelDownloadLogEvent");
        zzfa zzfa5 = new zzfa();
        zzfa5.zza(3);
        zzf = a6.b(zzfa5.zzb()).a();
        d.b a7 = d.a("customModelLoadLogEvent");
        zzfa zzfa6 = new zzfa();
        zzfa6.zza(20);
        zzg = a7.b(zzfa6.zzb()).a();
        d.b a8 = d.a("customModelInferenceLogEvent");
        zzfa zzfa7 = new zzfa();
        zzfa7.zza(4);
        zzh = a8.b(zzfa7.zzb()).a();
        d.b a9 = d.a("customModelCreateLogEvent");
        zzfa zzfa8 = new zzfa();
        zzfa8.zza(29);
        zzi = a9.b(zzfa8.zzb()).a();
        d.b a10 = d.a("onDeviceFaceDetectionLogEvent");
        zzfa zzfa9 = new zzfa();
        zzfa9.zza(5);
        zzj = a10.b(zzfa9.zzb()).a();
        d.b a11 = d.a("onDeviceFaceLoadLogEvent");
        zzfa zzfa10 = new zzfa();
        zzfa10.zza(59);
        zzk = a11.b(zzfa10.zzb()).a();
        d.b a12 = d.a("onDeviceTextDetectionLogEvent");
        zzfa zzfa11 = new zzfa();
        zzfa11.zza(6);
        zzl = a12.b(zzfa11.zzb()).a();
        d.b a13 = d.a("onDeviceTextDetectionLoadLogEvent");
        zzfa zzfa12 = new zzfa();
        zzfa12.zza(79);
        zzm = a13.b(zzfa12.zzb()).a();
        d.b a14 = d.a("onDeviceBarcodeDetectionLogEvent");
        zzfa zzfa13 = new zzfa();
        zzfa13.zza(7);
        zzn = a14.b(zzfa13.zzb()).a();
        d.b a15 = d.a("onDeviceBarcodeLoadLogEvent");
        zzfa zzfa14 = new zzfa();
        zzfa14.zza(58);
        zzo = a15.b(zzfa14.zzb()).a();
        d.b a16 = d.a("onDeviceImageLabelCreateLogEvent");
        zzfa zzfa15 = new zzfa();
        zzfa15.zza(48);
        zzp = a16.b(zzfa15.zzb()).a();
        d.b a17 = d.a("onDeviceImageLabelLoadLogEvent");
        zzfa zzfa16 = new zzfa();
        zzfa16.zza(49);
        zzq = a17.b(zzfa16.zzb()).a();
        d.b a18 = d.a("onDeviceImageLabelDetectionLogEvent");
        zzfa zzfa17 = new zzfa();
        zzfa17.zza(18);
        zzr = a18.b(zzfa17.zzb()).a();
        d.b a19 = d.a("onDeviceObjectCreateLogEvent");
        zzfa zzfa18 = new zzfa();
        zzfa18.zza(26);
        zzs = a19.b(zzfa18.zzb()).a();
        d.b a20 = d.a("onDeviceObjectLoadLogEvent");
        zzfa zzfa19 = new zzfa();
        zzfa19.zza(27);
        zzt = a20.b(zzfa19.zzb()).a();
        d.b a21 = d.a("onDeviceObjectInferenceLogEvent");
        zzfa zzfa20 = new zzfa();
        zzfa20.zza(28);
        zzu = a21.b(zzfa20.zzb()).a();
        d.b a22 = d.a("onDevicePoseDetectionLogEvent");
        zzfa zzfa21 = new zzfa();
        zzfa21.zza(44);
        zzv = a22.b(zzfa21.zzb()).a();
        d.b a23 = d.a("onDeviceSegmentationLogEvent");
        zzfa zzfa22 = new zzfa();
        zzfa22.zza(45);
        zzw = a23.b(zzfa22.zzb()).a();
        d.b a24 = d.a("onDeviceSmartReplyLogEvent");
        zzfa zzfa23 = new zzfa();
        zzfa23.zza(19);
        zzx = a24.b(zzfa23.zzb()).a();
        d.b a25 = d.a("onDeviceLanguageIdentificationLogEvent");
        zzfa zzfa24 = new zzfa();
        zzfa24.zza(21);
        zzy = a25.b(zzfa24.zzb()).a();
        d.b a26 = d.a("onDeviceTranslationLogEvent");
        zzfa zzfa25 = new zzfa();
        zzfa25.zza(22);
        zzz = a26.b(zzfa25.zzb()).a();
        d.b a27 = d.a("cloudFaceDetectionLogEvent");
        zzfa zzfa26 = new zzfa();
        zzfa26.zza(8);
        zzA = a27.b(zzfa26.zzb()).a();
        d.b a28 = d.a("cloudCropHintDetectionLogEvent");
        zzfa zzfa27 = new zzfa();
        zzfa27.zza(9);
        zzB = a28.b(zzfa27.zzb()).a();
        d.b a29 = d.a("cloudDocumentTextDetectionLogEvent");
        zzfa zzfa28 = new zzfa();
        zzfa28.zza(10);
        zzC = a29.b(zzfa28.zzb()).a();
        d.b a30 = d.a("cloudImagePropertiesDetectionLogEvent");
        zzfa zzfa29 = new zzfa();
        zzfa29.zza(11);
        zzD = a30.b(zzfa29.zzb()).a();
        d.b a31 = d.a("cloudImageLabelDetectionLogEvent");
        zzfa zzfa30 = new zzfa();
        zzfa30.zza(12);
        zzE = a31.b(zzfa30.zzb()).a();
        d.b a32 = d.a("cloudLandmarkDetectionLogEvent");
        zzfa zzfa31 = new zzfa();
        zzfa31.zza(13);
        zzF = a32.b(zzfa31.zzb()).a();
        d.b a33 = d.a("cloudLogoDetectionLogEvent");
        zzfa zzfa32 = new zzfa();
        zzfa32.zza(14);
        zzG = a33.b(zzfa32.zzb()).a();
        d.b a34 = d.a("cloudSafeSearchDetectionLogEvent");
        zzfa zzfa33 = new zzfa();
        zzfa33.zza(15);
        zzH = a34.b(zzfa33.zzb()).a();
        d.b a35 = d.a("cloudTextDetectionLogEvent");
        zzfa zzfa34 = new zzfa();
        zzfa34.zza(16);
        zzI = a35.b(zzfa34.zzb()).a();
        d.b a36 = d.a("cloudWebSearchDetectionLogEvent");
        zzfa zzfa35 = new zzfa();
        zzfa35.zza(17);
        zzJ = a36.b(zzfa35.zzb()).a();
        d.b a37 = d.a("automlImageLabelingCreateLogEvent");
        zzfa zzfa36 = new zzfa();
        zzfa36.zza(23);
        zzK = a37.b(zzfa36.zzb()).a();
        d.b a38 = d.a("automlImageLabelingLoadLogEvent");
        zzfa zzfa37 = new zzfa();
        zzfa37.zza(24);
        zzL = a38.b(zzfa37.zzb()).a();
        d.b a39 = d.a("automlImageLabelingInferenceLogEvent");
        zzfa zzfa38 = new zzfa();
        zzfa38.zza(25);
        zzM = a39.b(zzfa38.zzb()).a();
        d.b a40 = d.a("isModelDownloadedLogEvent");
        zzfa zzfa39 = new zzfa();
        zzfa39.zza(39);
        zzN = a40.b(zzfa39.zzb()).a();
        d.b a41 = d.a("deleteModelLogEvent");
        zzfa zzfa40 = new zzfa();
        zzfa40.zza(40);
        zzO = a41.b(zzfa40.zzb()).a();
        d.b a42 = d.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzfa zzfa41 = new zzfa();
        zzfa41.zza(30);
        zzP = a42.b(zzfa41.zzb()).a();
        d.b a43 = d.a("aggregatedCustomModelInferenceLogEvent");
        zzfa zzfa42 = new zzfa();
        zzfa42.zza(31);
        zzQ = a43.b(zzfa42.zzb()).a();
        d.b a44 = d.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzfa zzfa43 = new zzfa();
        zzfa43.zza(32);
        zzR = a44.b(zzfa43.zzb()).a();
        d.b a45 = d.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzfa zzfa44 = new zzfa();
        zzfa44.zza(33);
        zzS = a45.b(zzfa44.zzb()).a();
        d.b a46 = d.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzfa zzfa45 = new zzfa();
        zzfa45.zza(34);
        zzT = a46.b(zzfa45.zzb()).a();
        d.b a47 = d.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzfa zzfa46 = new zzfa();
        zzfa46.zza(35);
        zzU = a47.b(zzfa46.zzb()).a();
        d.b a48 = d.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzfa zzfa47 = new zzfa();
        zzfa47.zza(36);
        zzV = a48.b(zzfa47.zzb()).a();
        d.b a49 = d.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzfa zzfa48 = new zzfa();
        zzfa48.zza(46);
        zzW = a49.b(zzfa48.zzb()).a();
        d.b a50 = d.a("aggregatedOnDeviceSegmentationLogEvent");
        zzfa zzfa49 = new zzfa();
        zzfa49.zza(47);
        zzX = a50.b(zzfa49.zzb()).a();
        d.b a51 = d.a("pipelineAccelerationInferenceEvents");
        zzfa zzfa50 = new zzfa();
        zzfa50.zza(69);
        zzY = a51.b(zzfa50.zzb()).a();
        d.b a52 = d.a("remoteConfigLogEvent");
        zzfa zzfa51 = new zzfa();
        zzfa51.zza(42);
        zzZ = a52.b(zzfa51.zzb()).a();
        d.b a53 = d.a("inputImageConstructionLogEvent");
        zzfa zzfa52 = new zzfa();
        zzfa52.zza(50);
        zzaa = a53.b(zzfa52.zzb()).a();
        d.b a54 = d.a("leakedHandleEvent");
        zzfa zzfa53 = new zzfa();
        zzfa53.zza(51);
        zzab = a54.b(zzfa53.zzb()).a();
        d.b a55 = d.a("cameraSourceLogEvent");
        zzfa zzfa54 = new zzfa();
        zzfa54.zza(52);
        zzac = a55.b(zzfa54.zzb()).a();
        d.b a56 = d.a("imageLabelOptionalModuleLogEvent");
        zzfa zzfa55 = new zzfa();
        zzfa55.zza(53);
        zzad = a56.b(zzfa55.zzb()).a();
        d.b a57 = d.a("languageIdentificationOptionalModuleLogEvent");
        zzfa zzfa56 = new zzfa();
        zzfa56.zza(54);
        zzae = a57.b(zzfa56.zzb()).a();
        d.b a58 = d.a("faceDetectionOptionalModuleLogEvent");
        zzfa zzfa57 = new zzfa();
        zzfa57.zza(60);
        zzaf = a58.b(zzfa57.zzb()).a();
        d.b a59 = d.a("documentDetectionOptionalModuleLogEvent");
        zzfa zzfa58 = new zzfa();
        zzfa58.zza(85);
        zzag = a59.b(zzfa58.zzb()).a();
        d.b a60 = d.a("documentCroppingOptionalModuleLogEvent");
        zzfa zzfa59 = new zzfa();
        zzfa59.zza(86);
        zzah = a60.b(zzfa59.zzb()).a();
        d.b a61 = d.a("documentEnhancementOptionalModuleLogEvent");
        zzfa zzfa60 = new zzfa();
        zzfa60.zza(87);
        zzai = a61.b(zzfa60.zzb()).a();
        d.b a62 = d.a("nlClassifierOptionalModuleLogEvent");
        zzfa zzfa61 = new zzfa();
        zzfa61.zza(55);
        zzaj = a62.b(zzfa61.zzb()).a();
        d.b a63 = d.a("nlClassifierClientLibraryLogEvent");
        zzfa zzfa62 = new zzfa();
        zzfa62.zza(56);
        zzak = a63.b(zzfa62.zzb()).a();
        d.b a64 = d.a("accelerationAllowlistLogEvent");
        zzfa zzfa63 = new zzfa();
        zzfa63.zza(57);
        zzal = a64.b(zzfa63.zzb()).a();
        d.b a65 = d.a("toxicityDetectionCreateEvent");
        zzfa zzfa64 = new zzfa();
        zzfa64.zza(62);
        zzam = a65.b(zzfa64.zzb()).a();
        d.b a66 = d.a("toxicityDetectionLoadEvent");
        zzfa zzfa65 = new zzfa();
        zzfa65.zza(63);
        zzan = a66.b(zzfa65.zzb()).a();
        d.b a67 = d.a("toxicityDetectionInferenceEvent");
        zzfa zzfa66 = new zzfa();
        zzfa66.zza(64);
        zzao = a67.b(zzfa66.zzb()).a();
        d.b a68 = d.a("barcodeDetectionOptionalModuleLogEvent");
        zzfa zzfa67 = new zzfa();
        zzfa67.zza(65);
        zzap = a68.b(zzfa67.zzb()).a();
        d.b a69 = d.a("customImageLabelOptionalModuleLogEvent");
        zzfa zzfa68 = new zzfa();
        zzfa68.zza(66);
        zzaq = a69.b(zzfa68.zzb()).a();
        d.b a70 = d.a("codeScannerScanApiEvent");
        zzfa zzfa69 = new zzfa();
        zzfa69.zza(67);
        zzar = a70.b(zzfa69.zzb()).a();
        d.b a71 = d.a("codeScannerOptionalModuleEvent");
        zzfa zzfa70 = new zzfa();
        zzfa70.zza(68);
        zzas = a71.b(zzfa70.zzb()).a();
        d.b a72 = d.a("onDeviceExplicitContentCreateLogEvent");
        zzfa zzfa71 = new zzfa();
        zzfa71.zza(70);
        zzat = a72.b(zzfa71.zzb()).a();
        d.b a73 = d.a("onDeviceExplicitContentLoadLogEvent");
        zzfa zzfa72 = new zzfa();
        zzfa72.zza(71);
        zzau = a73.b(zzfa72.zzb()).a();
        d.b a74 = d.a("onDeviceExplicitContentInferenceLogEvent");
        zzfa zzfa73 = new zzfa();
        zzfa73.zza(72);
        zzav = a74.b(zzfa73.zzb()).a();
        d.b a75 = d.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzfa zzfa74 = new zzfa();
        zzfa74.zza(73);
        zzaw = a75.b(zzfa74.zzb()).a();
        d.b a76 = d.a("onDeviceFaceMeshCreateLogEvent");
        zzfa zzfa75 = new zzfa();
        zzfa75.zza(74);
        zzax = a76.b(zzfa75.zzb()).a();
        d.b a77 = d.a("onDeviceFaceMeshLoadLogEvent");
        zzfa zzfa76 = new zzfa();
        zzfa76.zza(75);
        zzay = a77.b(zzfa76.zzb()).a();
        d.b a78 = d.a("onDeviceFaceMeshLogEvent");
        zzfa zzfa77 = new zzfa();
        zzfa77.zza(76);
        zzaz = a78.b(zzfa77.zzb()).a();
        d.b a79 = d.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzfa zzfa78 = new zzfa();
        zzfa78.zza(77);
        zzaA = a79.b(zzfa78.zzb()).a();
        d.b a80 = d.a("smartReplyOptionalModuleLogEvent");
        zzfa zzfa79 = new zzfa();
        zzfa79.zza(78);
        zzaB = a80.b(zzfa79.zzb()).a();
        d.b a81 = d.a("textDetectionOptionalModuleLogEvent");
        zzfa zzfa80 = new zzfa();
        zzfa80.zza(80);
        zzaC = a81.b(zzfa80.zzb()).a();
        d.b a82 = d.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzfa zzfa81 = new zzfa();
        zzfa81.zza(81);
        zzaD = a82.b(zzfa81.zzb()).a();
        d.b a83 = d.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzfa zzfa82 = new zzfa();
        zzfa82.zza(82);
        zzaE = a83.b(zzfa82.zzb()).a();
        d.b a84 = d.a("onDeviceImageQualityAnalysisLogEvent");
        zzfa zzfa83 = new zzfa();
        zzfa83.zza(83);
        zzaF = a84.b(zzfa83.zzb()).a();
        d.b a85 = d.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzfa zzfa84 = new zzfa();
        zzfa84.zza(84);
        zzaG = a85.b(zzfa84.zzb()).a();
        d.b a86 = d.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzfa zzfa85 = new zzfa();
        zzfa85.zza(88);
        zzaH = a86.b(zzfa85.zzb()).a();
        d.b a87 = d.a("imageCaptioningOptionalModuleLogEvent");
        zzfa zzfa86 = new zzfa();
        zzfa86.zza(89);
        zzaI = a87.b(zzfa86.zzb()).a();
        d.b a88 = d.a("onDeviceImageCaptioningCreateLogEvent");
        zzfa zzfa87 = new zzfa();
        zzfa87.zza(90);
        zzaJ = a88.b(zzfa87.zzb()).a();
        d.b a89 = d.a("onDeviceImageCaptioningLoadLogEvent");
        zzfa zzfa88 = new zzfa();
        zzfa88.zza(91);
        zzaK = a89.b(zzfa88.zzb()).a();
        d.b a90 = d.a("onDeviceImageCaptioningInferenceLogEvent");
        zzfa zzfa89 = new zzfa();
        zzfa89.zza(92);
        zzaL = a90.b(zzfa89.zzb()).a();
        d.b a91 = d.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzfa zzfa90 = new zzfa();
        zzfa90.zza(93);
        zzaM = a91.b(zzfa90.zzb()).a();
        d.b a92 = d.a("onDeviceDocumentDetectionCreateLogEvent");
        zzfa zzfa91 = new zzfa();
        zzfa91.zza(94);
        zzaN = a92.b(zzfa91.zzb()).a();
        d.b a93 = d.a("onDeviceDocumentDetectionLoadLogEvent");
        zzfa zzfa92 = new zzfa();
        zzfa92.zza(95);
        zzaO = a93.b(zzfa92.zzb()).a();
        d.b a94 = d.a("onDeviceDocumentDetectionLogEvent");
        zzfa zzfa93 = new zzfa();
        zzfa93.zza(96);
        zzaP = a94.b(zzfa93.zzb()).a();
        d.b a95 = d.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzfa zzfa94 = new zzfa();
        zzfa94.zza(97);
        zzaQ = a95.b(zzfa94.zzb()).a();
        d.b a96 = d.a("onDeviceDocumentCroppingCreateLogEvent");
        zzfa zzfa95 = new zzfa();
        zzfa95.zza(98);
        zzaR = a96.b(zzfa95.zzb()).a();
        d.b a97 = d.a("onDeviceDocumentCroppingLoadLogEvent");
        zzfa zzfa96 = new zzfa();
        zzfa96.zza(99);
        zzaS = a97.b(zzfa96.zzb()).a();
        d.b a98 = d.a("onDeviceDocumentCroppingLogEvent");
        zzfa zzfa97 = new zzfa();
        zzfa97.zza(100);
        zzaT = a98.b(zzfa97.zzb()).a();
        d.b a99 = d.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzfa zzfa98 = new zzfa();
        zzfa98.zza(LDSFile.EF_DG5_TAG);
        zzaU = a99.b(zzfa98.zzb()).a();
        d.b a100 = d.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzfa zzfa99 = new zzfa();
        zzfa99.zza(LDSFile.EF_DG6_TAG);
        zzaV = a100.b(zzfa99.zzb()).a();
        d.b a101 = d.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzfa zzfa100 = new zzfa();
        zzfa100.zza(LDSFile.EF_DG7_TAG);
        zzaW = a101.b(zzfa100.zzb()).a();
        d.b a102 = d.a("onDeviceDocumentEnhancementLogEvent");
        zzfa zzfa101 = new zzfa();
        zzfa101.zza(LDSFile.EF_DG8_TAG);
        zzaX = a102.b(zzfa101.zzb()).a();
        d.b a103 = d.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzfa zzfa102 = new zzfa();
        zzfa102.zza(LDSFile.EF_DG9_TAG);
        zzaY = a103.b(zzfa102.zzb()).a();
        d.b a104 = d.a("scannerAutoZoomEvent");
        zzfa zzfa103 = new zzfa();
        zzfa103.zza(LDSFile.EF_DG10_TAG);
        zzaZ = a104.b(zzfa103.zzb()).a();
        d.b a105 = d.a("lowLightAutoExposureComputationEvent");
        zzfa zzfa104 = new zzfa();
        zzfa104.zza(LDSFile.EF_DG11_TAG);
        zzba = a105.b(zzfa104.zzb()).a();
        d.b a106 = d.a("lowLightFrameProcessEvent");
        zzfa zzfa105 = new zzfa();
        zzfa105.zza(LDSFile.EF_DG12_TAG);
        zzbb = a106.b(zzfa105.zzb()).a();
        d.b a107 = d.a("lowLightSceneDetectionEvent");
        zzfa zzfa106 = new zzfa();
        zzfa106.zza(LDSFile.EF_DG13_TAG);
        zzbc = a107.b(zzfa106.zzb()).a();
        d.b a108 = d.a("onDeviceStainRemovalLogEvent");
        zzfa zzfa107 = new zzfa();
        zzfa107.zza(LDSFile.EF_DG14_TAG);
        zzbd = a108.b(zzfa107.zzb()).a();
        d.b a109 = d.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzfa zzfa108 = new zzfa();
        zzfa108.zza(LDSFile.EF_DG15_TAG);
        zzbe = a109.b(zzfa108.zzb()).a();
        d.b a110 = d.a("stainRemovalOptionalModuleLogEvent");
        zzfa zzfa109 = new zzfa();
        zzfa109.zza(LDSFile.EF_DG16_TAG);
        zzbf = a110.b(zzfa109.zzb()).a();
        d.b a111 = d.a("onDeviceShadowRemovalLogEvent");
        zzfa zzfa110 = new zzfa();
        zzfa110.zza(113);
        zzbg = a111.b(zzfa110.zzb()).a();
        d.b a112 = d.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzfa zzfa111 = new zzfa();
        zzfa111.zza(114);
        zzbh = a112.b(zzfa111.zzb()).a();
        d.b a113 = d.a("shadowRemovalOptionalModuleLogEvent");
        zzfa zzfa112 = new zzfa();
        zzfa112.zza(ISO781611.DISCRETIONARY_DATA_FOR_PAYLOAD_CONSTRUCTED_TAG);
        zzbi = a113.b(zzfa112.zzb()).a();
        d.b a114 = d.a("onDeviceDigitalInkSegmentationLogEvent");
        zzfa zzfa113 = new zzfa();
        zzfa113.zza(116);
        zzbj = a114.b(zzfa113.zzb()).a();
        d.b a115 = d.a("onDeviceDocumentScannerStartLogEvent");
        zzfa zzfa114 = new zzfa();
        zzfa114.zza(LDSFile.EF_DG2_TAG);
        zzbk = a115.b(zzfa114.zzb()).a();
        d.b a116 = d.a("onDeviceDocumentScannerFinishLogEvent");
        zzfa zzfa115 = new zzfa();
        zzfa115.zza(LDSFile.EF_DG4_TAG);
        zzbl = a116.b(zzfa115.zzb()).a();
        d.b a117 = d.a("onDeviceDocumentScannerUiStartLogEvent");
        zzfa zzfa116 = new zzfa();
        zzfa116.zza(LDSFile.EF_SOD_TAG);
        zzbm = a117.b(zzfa116.zzb()).a();
        d.b a118 = d.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzfa zzfa117 = new zzfa();
        zzfa117.zza(120);
        zzbn = a118.b(zzfa117.zzb()).a();
        d.b a119 = d.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzfa zzfa118 = new zzfa();
        zzfa118.zza(121);
        zzbo = a119.b(zzfa118.zzb()).a();
        d.b a120 = d.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzfa zzfa119 = new zzfa();
        zzfa119.zza(122);
        zzbp = a120.b(zzfa119.zzb()).a();
        d.b a121 = d.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzfa zzfa120 = new zzfa();
        zzfa120.zza(123);
        zzbq = a121.b(zzfa120.zzb()).a();
        d.b a122 = d.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzfa zzfa121 = new zzfa();
        zzfa121.zza(124);
        zzbr = a122.b(zzfa121.zzb()).a();
        d.b a123 = d.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzfa zzfa122 = new zzfa();
        zzfa122.zza(ISO781611.SMT_TAG);
        zzbs = a123.b(zzfa122.zzb()).a();
        d.b a124 = d.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzfa zzfa123 = new zzfa();
        zzfa123.zza(126);
        zzbt = a124.b(zzfa123.zzb()).a();
        d.b a125 = d.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzfa zzfa124 = new zzfa();
        zzfa124.zza(CertificateBody.profileType);
        zzbu = a125.b(zzfa124.zzb()).a();
        d.b a126 = d.a("subjectSegmentationOptionalModuleLogEvent");
        zzfa zzfa125 = new zzfa();
        zzfa125.zza(128);
        zzbv = a126.b(zzfa125.zzb()).a();
        d.b a127 = d.a("documentScannerUiModuleScreenViewEvent");
        zzfa zzfa126 = new zzfa();
        zzfa126.zza(129);
        zzbw = a127.b(zzfa126.zzb()).a();
        d.b a128 = d.a("documentScannerUiModuleScreenClickEvent");
        zzfa zzfa127 = new zzfa();
        zzfa127.zza(ISO781611.BIOMETRIC_SUBTYPE_TAG);
        zzbx = a128.b(zzfa127.zzb()).a();
        d.b a129 = d.a("documentScannerUiModuleScreenErrorEvent");
        zzfa zzfa128 = new zzfa();
        zzfa128.zza(ISO781611.CREATION_DATE_AND_TIME_TAG);
        zzby = a129.b(zzfa128.zzb()).a();
    }

    private zzkv() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzrf zzrf = (zzrf) obj;
        f fVar = (f) obj2;
        fVar.add(zzb, zzrf.zzg());
        fVar.add(zzc, zzrf.zzc());
        fVar.add(zzd, (Object) null);
        fVar.add(zze, zzrf.zzb());
        fVar.add(zzf, (Object) null);
        fVar.add(zzg, (Object) null);
        fVar.add(zzh, (Object) null);
        fVar.add(zzi, (Object) null);
        fVar.add(zzj, (Object) null);
        fVar.add(zzk, (Object) null);
        fVar.add(zzl, (Object) null);
        fVar.add(zzm, (Object) null);
        fVar.add(zzn, zzrf.zzd());
        fVar.add(zzo, zzrf.zze());
        fVar.add(zzp, (Object) null);
        fVar.add(zzq, (Object) null);
        fVar.add(zzr, (Object) null);
        fVar.add(zzs, (Object) null);
        fVar.add(zzt, (Object) null);
        fVar.add(zzu, (Object) null);
        fVar.add(zzv, (Object) null);
        fVar.add(zzw, (Object) null);
        fVar.add(zzx, (Object) null);
        fVar.add(zzy, (Object) null);
        fVar.add(zzz, (Object) null);
        fVar.add(zzA, (Object) null);
        fVar.add(zzB, (Object) null);
        fVar.add(zzC, (Object) null);
        fVar.add(zzD, (Object) null);
        fVar.add(zzE, (Object) null);
        fVar.add(zzF, (Object) null);
        fVar.add(zzG, (Object) null);
        fVar.add(zzH, (Object) null);
        fVar.add(zzI, (Object) null);
        fVar.add(zzJ, (Object) null);
        fVar.add(zzK, (Object) null);
        fVar.add(zzL, (Object) null);
        fVar.add(zzM, (Object) null);
        fVar.add(zzN, (Object) null);
        fVar.add(zzO, (Object) null);
        fVar.add(zzP, (Object) null);
        fVar.add(zzQ, (Object) null);
        fVar.add(zzR, (Object) null);
        fVar.add(zzS, zzrf.zza());
        fVar.add(zzT, (Object) null);
        fVar.add(zzU, (Object) null);
        fVar.add(zzV, (Object) null);
        fVar.add(zzW, (Object) null);
        fVar.add(zzX, (Object) null);
        fVar.add(zzY, (Object) null);
        fVar.add(zzZ, (Object) null);
        fVar.add(zzaa, (Object) null);
        fVar.add(zzab, (Object) null);
        fVar.add(zzac, (Object) null);
        fVar.add(zzad, (Object) null);
        fVar.add(zzae, (Object) null);
        fVar.add(zzaf, (Object) null);
        fVar.add(zzag, (Object) null);
        fVar.add(zzah, (Object) null);
        fVar.add(zzai, (Object) null);
        fVar.add(zzaj, (Object) null);
        fVar.add(zzak, (Object) null);
        fVar.add(zzal, (Object) null);
        fVar.add(zzam, (Object) null);
        fVar.add(zzan, (Object) null);
        fVar.add(zzao, (Object) null);
        fVar.add(zzap, (Object) null);
        fVar.add(zzaq, (Object) null);
        fVar.add(zzar, (Object) null);
        fVar.add(zzas, (Object) null);
        fVar.add(zzat, (Object) null);
        fVar.add(zzau, (Object) null);
        fVar.add(zzav, (Object) null);
        fVar.add(zzaw, (Object) null);
        fVar.add(zzax, (Object) null);
        fVar.add(zzay, (Object) null);
        fVar.add(zzaz, (Object) null);
        fVar.add(zzaA, (Object) null);
        fVar.add(zzaB, (Object) null);
        fVar.add(zzaC, (Object) null);
        fVar.add(zzaD, (Object) null);
        fVar.add(zzaE, (Object) null);
        fVar.add(zzaF, (Object) null);
        fVar.add(zzaG, (Object) null);
        fVar.add(zzaH, (Object) null);
        fVar.add(zzaI, (Object) null);
        fVar.add(zzaJ, (Object) null);
        fVar.add(zzaK, (Object) null);
        fVar.add(zzaL, (Object) null);
        fVar.add(zzaM, (Object) null);
        fVar.add(zzaN, (Object) null);
        fVar.add(zzaO, (Object) null);
        fVar.add(zzaP, (Object) null);
        fVar.add(zzaQ, (Object) null);
        fVar.add(zzaR, (Object) null);
        fVar.add(zzaS, (Object) null);
        fVar.add(zzaT, (Object) null);
        fVar.add(zzaU, (Object) null);
        fVar.add(zzaV, (Object) null);
        fVar.add(zzaW, (Object) null);
        fVar.add(zzaX, (Object) null);
        fVar.add(zzaY, (Object) null);
        fVar.add(zzaZ, zzrf.zzf());
        fVar.add(zzba, (Object) null);
        fVar.add(zzbb, (Object) null);
        fVar.add(zzbc, (Object) null);
        fVar.add(zzbd, (Object) null);
        fVar.add(zzbe, (Object) null);
        fVar.add(zzbf, (Object) null);
        fVar.add(zzbg, (Object) null);
        fVar.add(zzbh, (Object) null);
        fVar.add(zzbi, (Object) null);
        fVar.add(zzbj, (Object) null);
        fVar.add(zzbk, (Object) null);
        fVar.add(zzbl, (Object) null);
        fVar.add(zzbm, (Object) null);
        fVar.add(zzbn, (Object) null);
        fVar.add(zzbo, (Object) null);
        fVar.add(zzbp, (Object) null);
        fVar.add(zzbq, (Object) null);
        fVar.add(zzbr, (Object) null);
        fVar.add(zzbs, (Object) null);
        fVar.add(zzbt, (Object) null);
        fVar.add(zzbu, (Object) null);
        fVar.add(zzbv, (Object) null);
        fVar.add(zzbw, (Object) null);
        fVar.add(zzbx, (Object) null);
        fVar.add(zzby, (Object) null);
    }
}
