package com.google.android.gms.internal.mlkit_common;

import G6.d;
import G6.e;
import G6.f;
import com.fis.ekyc.nfc.build_in.bouncycastle.asn1.eac.CertificateBody;
import com.fis.ekyc.nfc.build_in.eidparser.cbeff.ISO781611;
import com.fis.ekyc.nfc.build_in.eidparser.lds.LDSFile;
import java.io.IOException;

final class zzgp implements e {
    private static final d zzA;
    private static final d zzB;
    private static final d zzC;
    private static final d zzD;
    private static final d zzE;
    private static final d zzF;
    private static final d zzG;
    private static final d zzH;
    private static final d zzI;
    private static final d zzJ;
    private static final d zzK;
    private static final d zzL;
    private static final d zzM;
    private static final d zzN;
    private static final d zzO;
    private static final d zzP;
    private static final d zzQ;
    private static final d zzR;
    private static final d zzS;
    private static final d zzT;
    private static final d zzU;
    private static final d zzV;
    private static final d zzW;
    private static final d zzX;
    private static final d zzY;
    private static final d zzZ;
    static final zzgp zza = new zzgp();
    private static final d zzaA;
    private static final d zzaB;
    private static final d zzaC;
    private static final d zzaD;
    private static final d zzaE;
    private static final d zzaF;
    private static final d zzaG;
    private static final d zzaH;
    private static final d zzaI;
    private static final d zzaJ;
    private static final d zzaK;
    private static final d zzaL;
    private static final d zzaM;
    private static final d zzaN;
    private static final d zzaO;
    private static final d zzaP;
    private static final d zzaQ;
    private static final d zzaR;
    private static final d zzaS;
    private static final d zzaT;
    private static final d zzaU;
    private static final d zzaV;
    private static final d zzaW;
    private static final d zzaX;
    private static final d zzaY;
    private static final d zzaZ;
    private static final d zzaa;
    private static final d zzab;
    private static final d zzac;
    private static final d zzad;
    private static final d zzae;
    private static final d zzaf;
    private static final d zzag;
    private static final d zzah;
    private static final d zzai;
    private static final d zzaj;
    private static final d zzak;
    private static final d zzal;
    private static final d zzam;
    private static final d zzan;
    private static final d zzao;
    private static final d zzap;
    private static final d zzaq;
    private static final d zzar;
    private static final d zzas;
    private static final d zzat;
    private static final d zzau;
    private static final d zzav;
    private static final d zzaw;
    private static final d zzax;
    private static final d zzay;
    private static final d zzaz;
    private static final d zzb;
    private static final d zzba;
    private static final d zzbb;
    private static final d zzbc;
    private static final d zzbd;
    private static final d zzbe;
    private static final d zzbf;
    private static final d zzbg;
    private static final d zzbh;
    private static final d zzbi;
    private static final d zzbj;
    private static final d zzbk;
    private static final d zzbl;
    private static final d zzbm;
    private static final d zzbn;
    private static final d zzbo;
    private static final d zzbp;
    private static final d zzbq;
    private static final d zzbr;
    private static final d zzbs;
    private static final d zzbt;
    private static final d zzbu;
    private static final d zzbv;
    private static final d zzbw;
    private static final d zzbx;
    private static final d zzby;
    private static final d zzc;
    private static final d zzd;
    private static final d zze;
    private static final d zzf;
    private static final d zzg;
    private static final d zzh;
    private static final d zzi;
    private static final d zzj;
    private static final d zzk;
    private static final d zzl;
    private static final d zzm;
    private static final d zzn;
    private static final d zzo;
    private static final d zzp;
    private static final d zzq;
    private static final d zzr;
    private static final d zzs;
    private static final d zzt;
    private static final d zzu;
    private static final d zzv;
    private static final d zzw;
    private static final d zzx;
    private static final d zzy;
    private static final d zzz;

    static {
        d.b a = d.a("systemInfo");
        zzay zzay2 = new zzay();
        zzay2.zza(1);
        zzb = a.b(zzay2.zzb()).a();
        d.b a2 = d.a("eventName");
        zzay zzay3 = new zzay();
        zzay3.zza(2);
        zzc = a2.b(zzay3.zzb()).a();
        d.b a3 = d.a("isThickClient");
        zzay zzay4 = new zzay();
        zzay4.zza(37);
        zzd = a3.b(zzay4.zzb()).a();
        d.b a4 = d.a("clientType");
        zzay zzay5 = new zzay();
        zzay5.zza(61);
        zze = a4.b(zzay5.zzb()).a();
        d.b a6 = d.a("modelDownloadLogEvent");
        zzay zzay6 = new zzay();
        zzay6.zza(3);
        zzf = a6.b(zzay6.zzb()).a();
        d.b a7 = d.a("customModelLoadLogEvent");
        zzay zzay7 = new zzay();
        zzay7.zza(20);
        zzg = a7.b(zzay7.zzb()).a();
        d.b a8 = d.a("customModelInferenceLogEvent");
        zzay zzay8 = new zzay();
        zzay8.zza(4);
        zzh = a8.b(zzay8.zzb()).a();
        d.b a9 = d.a("customModelCreateLogEvent");
        zzay zzay9 = new zzay();
        zzay9.zza(29);
        zzi = a9.b(zzay9.zzb()).a();
        d.b a10 = d.a("onDeviceFaceDetectionLogEvent");
        zzay zzay10 = new zzay();
        zzay10.zza(5);
        zzj = a10.b(zzay10.zzb()).a();
        d.b a11 = d.a("onDeviceFaceLoadLogEvent");
        zzay zzay11 = new zzay();
        zzay11.zza(59);
        zzk = a11.b(zzay11.zzb()).a();
        d.b a12 = d.a("onDeviceTextDetectionLogEvent");
        zzay zzay12 = new zzay();
        zzay12.zza(6);
        zzl = a12.b(zzay12.zzb()).a();
        d.b a13 = d.a("onDeviceTextDetectionLoadLogEvent");
        zzay zzay13 = new zzay();
        zzay13.zza(79);
        zzm = a13.b(zzay13.zzb()).a();
        d.b a14 = d.a("onDeviceBarcodeDetectionLogEvent");
        zzay zzay14 = new zzay();
        zzay14.zza(7);
        zzn = a14.b(zzay14.zzb()).a();
        d.b a15 = d.a("onDeviceBarcodeLoadLogEvent");
        zzay zzay15 = new zzay();
        zzay15.zza(58);
        zzo = a15.b(zzay15.zzb()).a();
        d.b a16 = d.a("onDeviceImageLabelCreateLogEvent");
        zzay zzay16 = new zzay();
        zzay16.zza(48);
        zzp = a16.b(zzay16.zzb()).a();
        d.b a17 = d.a("onDeviceImageLabelLoadLogEvent");
        zzay zzay17 = new zzay();
        zzay17.zza(49);
        zzq = a17.b(zzay17.zzb()).a();
        d.b a18 = d.a("onDeviceImageLabelDetectionLogEvent");
        zzay zzay18 = new zzay();
        zzay18.zza(18);
        zzr = a18.b(zzay18.zzb()).a();
        d.b a19 = d.a("onDeviceObjectCreateLogEvent");
        zzay zzay19 = new zzay();
        zzay19.zza(26);
        zzs = a19.b(zzay19.zzb()).a();
        d.b a20 = d.a("onDeviceObjectLoadLogEvent");
        zzay zzay20 = new zzay();
        zzay20.zza(27);
        zzt = a20.b(zzay20.zzb()).a();
        d.b a21 = d.a("onDeviceObjectInferenceLogEvent");
        zzay zzay21 = new zzay();
        zzay21.zza(28);
        zzu = a21.b(zzay21.zzb()).a();
        d.b a22 = d.a("onDevicePoseDetectionLogEvent");
        zzay zzay22 = new zzay();
        zzay22.zza(44);
        zzv = a22.b(zzay22.zzb()).a();
        d.b a23 = d.a("onDeviceSegmentationLogEvent");
        zzay zzay23 = new zzay();
        zzay23.zza(45);
        zzw = a23.b(zzay23.zzb()).a();
        d.b a24 = d.a("onDeviceSmartReplyLogEvent");
        zzay zzay24 = new zzay();
        zzay24.zza(19);
        zzx = a24.b(zzay24.zzb()).a();
        d.b a25 = d.a("onDeviceLanguageIdentificationLogEvent");
        zzay zzay25 = new zzay();
        zzay25.zza(21);
        zzy = a25.b(zzay25.zzb()).a();
        d.b a26 = d.a("onDeviceTranslationLogEvent");
        zzay zzay26 = new zzay();
        zzay26.zza(22);
        zzz = a26.b(zzay26.zzb()).a();
        d.b a27 = d.a("cloudFaceDetectionLogEvent");
        zzay zzay27 = new zzay();
        zzay27.zza(8);
        zzA = a27.b(zzay27.zzb()).a();
        d.b a28 = d.a("cloudCropHintDetectionLogEvent");
        zzay zzay28 = new zzay();
        zzay28.zza(9);
        zzB = a28.b(zzay28.zzb()).a();
        d.b a29 = d.a("cloudDocumentTextDetectionLogEvent");
        zzay zzay29 = new zzay();
        zzay29.zza(10);
        zzC = a29.b(zzay29.zzb()).a();
        d.b a30 = d.a("cloudImagePropertiesDetectionLogEvent");
        zzay zzay30 = new zzay();
        zzay30.zza(11);
        zzD = a30.b(zzay30.zzb()).a();
        d.b a31 = d.a("cloudImageLabelDetectionLogEvent");
        zzay zzay31 = new zzay();
        zzay31.zza(12);
        zzE = a31.b(zzay31.zzb()).a();
        d.b a32 = d.a("cloudLandmarkDetectionLogEvent");
        zzay zzay32 = new zzay();
        zzay32.zza(13);
        zzF = a32.b(zzay32.zzb()).a();
        d.b a33 = d.a("cloudLogoDetectionLogEvent");
        zzay zzay33 = new zzay();
        zzay33.zza(14);
        zzG = a33.b(zzay33.zzb()).a();
        d.b a34 = d.a("cloudSafeSearchDetectionLogEvent");
        zzay zzay34 = new zzay();
        zzay34.zza(15);
        zzH = a34.b(zzay34.zzb()).a();
        d.b a35 = d.a("cloudTextDetectionLogEvent");
        zzay zzay35 = new zzay();
        zzay35.zza(16);
        zzI = a35.b(zzay35.zzb()).a();
        d.b a36 = d.a("cloudWebSearchDetectionLogEvent");
        zzay zzay36 = new zzay();
        zzay36.zza(17);
        zzJ = a36.b(zzay36.zzb()).a();
        d.b a37 = d.a("automlImageLabelingCreateLogEvent");
        zzay zzay37 = new zzay();
        zzay37.zza(23);
        zzK = a37.b(zzay37.zzb()).a();
        d.b a38 = d.a("automlImageLabelingLoadLogEvent");
        zzay zzay38 = new zzay();
        zzay38.zza(24);
        zzL = a38.b(zzay38.zzb()).a();
        d.b a39 = d.a("automlImageLabelingInferenceLogEvent");
        zzay zzay39 = new zzay();
        zzay39.zza(25);
        zzM = a39.b(zzay39.zzb()).a();
        d.b a40 = d.a("isModelDownloadedLogEvent");
        zzay zzay40 = new zzay();
        zzay40.zza(39);
        zzN = a40.b(zzay40.zzb()).a();
        d.b a41 = d.a("deleteModelLogEvent");
        zzay zzay41 = new zzay();
        zzay41.zza(40);
        zzO = a41.b(zzay41.zzb()).a();
        d.b a42 = d.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzay zzay42 = new zzay();
        zzay42.zza(30);
        zzP = a42.b(zzay42.zzb()).a();
        d.b a43 = d.a("aggregatedCustomModelInferenceLogEvent");
        zzay zzay43 = new zzay();
        zzay43.zza(31);
        zzQ = a43.b(zzay43.zzb()).a();
        d.b a44 = d.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzay zzay44 = new zzay();
        zzay44.zza(32);
        zzR = a44.b(zzay44.zzb()).a();
        d.b a45 = d.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzay zzay45 = new zzay();
        zzay45.zza(33);
        zzS = a45.b(zzay45.zzb()).a();
        d.b a46 = d.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzay zzay46 = new zzay();
        zzay46.zza(34);
        zzT = a46.b(zzay46.zzb()).a();
        d.b a47 = d.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzay zzay47 = new zzay();
        zzay47.zza(35);
        zzU = a47.b(zzay47.zzb()).a();
        d.b a48 = d.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzay zzay48 = new zzay();
        zzay48.zza(36);
        zzV = a48.b(zzay48.zzb()).a();
        d.b a49 = d.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzay zzay49 = new zzay();
        zzay49.zza(46);
        zzW = a49.b(zzay49.zzb()).a();
        d.b a50 = d.a("aggregatedOnDeviceSegmentationLogEvent");
        zzay zzay50 = new zzay();
        zzay50.zza(47);
        zzX = a50.b(zzay50.zzb()).a();
        d.b a51 = d.a("pipelineAccelerationInferenceEvents");
        zzay zzay51 = new zzay();
        zzay51.zza(69);
        zzY = a51.b(zzay51.zzb()).a();
        d.b a52 = d.a("remoteConfigLogEvent");
        zzay zzay52 = new zzay();
        zzay52.zza(42);
        zzZ = a52.b(zzay52.zzb()).a();
        d.b a53 = d.a("inputImageConstructionLogEvent");
        zzay zzay53 = new zzay();
        zzay53.zza(50);
        zzaa = a53.b(zzay53.zzb()).a();
        d.b a54 = d.a("leakedHandleEvent");
        zzay zzay54 = new zzay();
        zzay54.zza(51);
        zzab = a54.b(zzay54.zzb()).a();
        d.b a55 = d.a("cameraSourceLogEvent");
        zzay zzay55 = new zzay();
        zzay55.zza(52);
        zzac = a55.b(zzay55.zzb()).a();
        d.b a56 = d.a("imageLabelOptionalModuleLogEvent");
        zzay zzay56 = new zzay();
        zzay56.zza(53);
        zzad = a56.b(zzay56.zzb()).a();
        d.b a57 = d.a("languageIdentificationOptionalModuleLogEvent");
        zzay zzay57 = new zzay();
        zzay57.zza(54);
        zzae = a57.b(zzay57.zzb()).a();
        d.b a58 = d.a("faceDetectionOptionalModuleLogEvent");
        zzay zzay58 = new zzay();
        zzay58.zza(60);
        zzaf = a58.b(zzay58.zzb()).a();
        d.b a59 = d.a("documentDetectionOptionalModuleLogEvent");
        zzay zzay59 = new zzay();
        zzay59.zza(85);
        zzag = a59.b(zzay59.zzb()).a();
        d.b a60 = d.a("documentCroppingOptionalModuleLogEvent");
        zzay zzay60 = new zzay();
        zzay60.zza(86);
        zzah = a60.b(zzay60.zzb()).a();
        d.b a61 = d.a("documentEnhancementOptionalModuleLogEvent");
        zzay zzay61 = new zzay();
        zzay61.zza(87);
        zzai = a61.b(zzay61.zzb()).a();
        d.b a62 = d.a("nlClassifierOptionalModuleLogEvent");
        zzay zzay62 = new zzay();
        zzay62.zza(55);
        zzaj = a62.b(zzay62.zzb()).a();
        d.b a63 = d.a("nlClassifierClientLibraryLogEvent");
        zzay zzay63 = new zzay();
        zzay63.zza(56);
        zzak = a63.b(zzay63.zzb()).a();
        d.b a64 = d.a("accelerationAllowlistLogEvent");
        zzay zzay64 = new zzay();
        zzay64.zza(57);
        zzal = a64.b(zzay64.zzb()).a();
        d.b a65 = d.a("toxicityDetectionCreateEvent");
        zzay zzay65 = new zzay();
        zzay65.zza(62);
        zzam = a65.b(zzay65.zzb()).a();
        d.b a66 = d.a("toxicityDetectionLoadEvent");
        zzay zzay66 = new zzay();
        zzay66.zza(63);
        zzan = a66.b(zzay66.zzb()).a();
        d.b a67 = d.a("toxicityDetectionInferenceEvent");
        zzay zzay67 = new zzay();
        zzay67.zza(64);
        zzao = a67.b(zzay67.zzb()).a();
        d.b a68 = d.a("barcodeDetectionOptionalModuleLogEvent");
        zzay zzay68 = new zzay();
        zzay68.zza(65);
        zzap = a68.b(zzay68.zzb()).a();
        d.b a69 = d.a("customImageLabelOptionalModuleLogEvent");
        zzay zzay69 = new zzay();
        zzay69.zza(66);
        zzaq = a69.b(zzay69.zzb()).a();
        d.b a70 = d.a("codeScannerScanApiEvent");
        zzay zzay70 = new zzay();
        zzay70.zza(67);
        zzar = a70.b(zzay70.zzb()).a();
        d.b a71 = d.a("codeScannerOptionalModuleEvent");
        zzay zzay71 = new zzay();
        zzay71.zza(68);
        zzas = a71.b(zzay71.zzb()).a();
        d.b a72 = d.a("onDeviceExplicitContentCreateLogEvent");
        zzay zzay72 = new zzay();
        zzay72.zza(70);
        zzat = a72.b(zzay72.zzb()).a();
        d.b a73 = d.a("onDeviceExplicitContentLoadLogEvent");
        zzay zzay73 = new zzay();
        zzay73.zza(71);
        zzau = a73.b(zzay73.zzb()).a();
        d.b a74 = d.a("onDeviceExplicitContentInferenceLogEvent");
        zzay zzay74 = new zzay();
        zzay74.zza(72);
        zzav = a74.b(zzay74.zzb()).a();
        d.b a75 = d.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzay zzay75 = new zzay();
        zzay75.zza(73);
        zzaw = a75.b(zzay75.zzb()).a();
        d.b a76 = d.a("onDeviceFaceMeshCreateLogEvent");
        zzay zzay76 = new zzay();
        zzay76.zza(74);
        zzax = a76.b(zzay76.zzb()).a();
        d.b a77 = d.a("onDeviceFaceMeshLoadLogEvent");
        zzay zzay77 = new zzay();
        zzay77.zza(75);
        zzay = a77.b(zzay77.zzb()).a();
        d.b a78 = d.a("onDeviceFaceMeshLogEvent");
        zzay zzay78 = new zzay();
        zzay78.zza(76);
        zzaz = a78.b(zzay78.zzb()).a();
        d.b a79 = d.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzay zzay79 = new zzay();
        zzay79.zza(77);
        zzaA = a79.b(zzay79.zzb()).a();
        d.b a80 = d.a("smartReplyOptionalModuleLogEvent");
        zzay zzay80 = new zzay();
        zzay80.zza(78);
        zzaB = a80.b(zzay80.zzb()).a();
        d.b a81 = d.a("textDetectionOptionalModuleLogEvent");
        zzay zzay81 = new zzay();
        zzay81.zza(80);
        zzaC = a81.b(zzay81.zzb()).a();
        d.b a82 = d.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzay zzay82 = new zzay();
        zzay82.zza(81);
        zzaD = a82.b(zzay82.zzb()).a();
        d.b a83 = d.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzay zzay83 = new zzay();
        zzay83.zza(82);
        zzaE = a83.b(zzay83.zzb()).a();
        d.b a84 = d.a("onDeviceImageQualityAnalysisLogEvent");
        zzay zzay84 = new zzay();
        zzay84.zza(83);
        zzaF = a84.b(zzay84.zzb()).a();
        d.b a85 = d.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzay zzay85 = new zzay();
        zzay85.zza(84);
        zzaG = a85.b(zzay85.zzb()).a();
        d.b a86 = d.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzay zzay86 = new zzay();
        zzay86.zza(88);
        zzaH = a86.b(zzay86.zzb()).a();
        d.b a87 = d.a("imageCaptioningOptionalModuleLogEvent");
        zzay zzay87 = new zzay();
        zzay87.zza(89);
        zzaI = a87.b(zzay87.zzb()).a();
        d.b a88 = d.a("onDeviceImageCaptioningCreateLogEvent");
        zzay zzay88 = new zzay();
        zzay88.zza(90);
        zzaJ = a88.b(zzay88.zzb()).a();
        d.b a89 = d.a("onDeviceImageCaptioningLoadLogEvent");
        zzay zzay89 = new zzay();
        zzay89.zza(91);
        zzaK = a89.b(zzay89.zzb()).a();
        d.b a90 = d.a("onDeviceImageCaptioningInferenceLogEvent");
        zzay zzay90 = new zzay();
        zzay90.zza(92);
        zzaL = a90.b(zzay90.zzb()).a();
        d.b a91 = d.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzay zzay91 = new zzay();
        zzay91.zza(93);
        zzaM = a91.b(zzay91.zzb()).a();
        d.b a92 = d.a("onDeviceDocumentDetectionCreateLogEvent");
        zzay zzay92 = new zzay();
        zzay92.zza(94);
        zzaN = a92.b(zzay92.zzb()).a();
        d.b a93 = d.a("onDeviceDocumentDetectionLoadLogEvent");
        zzay zzay93 = new zzay();
        zzay93.zza(95);
        zzaO = a93.b(zzay93.zzb()).a();
        d.b a94 = d.a("onDeviceDocumentDetectionLogEvent");
        zzay zzay94 = new zzay();
        zzay94.zza(96);
        zzaP = a94.b(zzay94.zzb()).a();
        d.b a95 = d.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzay zzay95 = new zzay();
        zzay95.zza(97);
        zzaQ = a95.b(zzay95.zzb()).a();
        d.b a96 = d.a("onDeviceDocumentCroppingCreateLogEvent");
        zzay zzay96 = new zzay();
        zzay96.zza(98);
        zzaR = a96.b(zzay96.zzb()).a();
        d.b a97 = d.a("onDeviceDocumentCroppingLoadLogEvent");
        zzay zzay97 = new zzay();
        zzay97.zza(99);
        zzaS = a97.b(zzay97.zzb()).a();
        d.b a98 = d.a("onDeviceDocumentCroppingLogEvent");
        zzay zzay98 = new zzay();
        zzay98.zza(100);
        zzaT = a98.b(zzay98.zzb()).a();
        d.b a99 = d.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzay zzay99 = new zzay();
        zzay99.zza(LDSFile.EF_DG5_TAG);
        zzaU = a99.b(zzay99.zzb()).a();
        d.b a100 = d.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzay zzay100 = new zzay();
        zzay100.zza(LDSFile.EF_DG6_TAG);
        zzaV = a100.b(zzay100.zzb()).a();
        d.b a101 = d.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzay zzay101 = new zzay();
        zzay101.zza(LDSFile.EF_DG7_TAG);
        zzaW = a101.b(zzay101.zzb()).a();
        d.b a102 = d.a("onDeviceDocumentEnhancementLogEvent");
        zzay zzay102 = new zzay();
        zzay102.zza(LDSFile.EF_DG8_TAG);
        zzaX = a102.b(zzay102.zzb()).a();
        d.b a103 = d.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzay zzay103 = new zzay();
        zzay103.zza(LDSFile.EF_DG9_TAG);
        zzaY = a103.b(zzay103.zzb()).a();
        d.b a104 = d.a("scannerAutoZoomEvent");
        zzay zzay104 = new zzay();
        zzay104.zza(LDSFile.EF_DG10_TAG);
        zzaZ = a104.b(zzay104.zzb()).a();
        d.b a105 = d.a("lowLightAutoExposureComputationEvent");
        zzay zzay105 = new zzay();
        zzay105.zza(LDSFile.EF_DG11_TAG);
        zzba = a105.b(zzay105.zzb()).a();
        d.b a106 = d.a("lowLightFrameProcessEvent");
        zzay zzay106 = new zzay();
        zzay106.zza(LDSFile.EF_DG12_TAG);
        zzbb = a106.b(zzay106.zzb()).a();
        d.b a107 = d.a("lowLightSceneDetectionEvent");
        zzay zzay107 = new zzay();
        zzay107.zza(LDSFile.EF_DG13_TAG);
        zzbc = a107.b(zzay107.zzb()).a();
        d.b a108 = d.a("onDeviceStainRemovalLogEvent");
        zzay zzay108 = new zzay();
        zzay108.zza(LDSFile.EF_DG14_TAG);
        zzbd = a108.b(zzay108.zzb()).a();
        d.b a109 = d.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzay zzay109 = new zzay();
        zzay109.zza(LDSFile.EF_DG15_TAG);
        zzbe = a109.b(zzay109.zzb()).a();
        d.b a110 = d.a("stainRemovalOptionalModuleLogEvent");
        zzay zzay110 = new zzay();
        zzay110.zza(LDSFile.EF_DG16_TAG);
        zzbf = a110.b(zzay110.zzb()).a();
        d.b a111 = d.a("onDeviceShadowRemovalLogEvent");
        zzay zzay111 = new zzay();
        zzay111.zza(113);
        zzbg = a111.b(zzay111.zzb()).a();
        d.b a112 = d.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzay zzay112 = new zzay();
        zzay112.zza(114);
        zzbh = a112.b(zzay112.zzb()).a();
        d.b a113 = d.a("shadowRemovalOptionalModuleLogEvent");
        zzay zzay113 = new zzay();
        zzay113.zza(ISO781611.DISCRETIONARY_DATA_FOR_PAYLOAD_CONSTRUCTED_TAG);
        zzbi = a113.b(zzay113.zzb()).a();
        d.b a114 = d.a("onDeviceDigitalInkSegmentationLogEvent");
        zzay zzay114 = new zzay();
        zzay114.zza(116);
        zzbj = a114.b(zzay114.zzb()).a();
        d.b a115 = d.a("onDeviceDocumentScannerStartLogEvent");
        zzay zzay115 = new zzay();
        zzay115.zza(LDSFile.EF_DG2_TAG);
        zzbk = a115.b(zzay115.zzb()).a();
        d.b a116 = d.a("onDeviceDocumentScannerFinishLogEvent");
        zzay zzay116 = new zzay();
        zzay116.zza(LDSFile.EF_DG4_TAG);
        zzbl = a116.b(zzay116.zzb()).a();
        d.b a117 = d.a("onDeviceDocumentScannerUiStartLogEvent");
        zzay zzay117 = new zzay();
        zzay117.zza(LDSFile.EF_SOD_TAG);
        zzbm = a117.b(zzay117.zzb()).a();
        d.b a118 = d.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzay zzay118 = new zzay();
        zzay118.zza(120);
        zzbn = a118.b(zzay118.zzb()).a();
        d.b a119 = d.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzay zzay119 = new zzay();
        zzay119.zza(121);
        zzbo = a119.b(zzay119.zzb()).a();
        d.b a120 = d.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzay zzay120 = new zzay();
        zzay120.zza(122);
        zzbp = a120.b(zzay120.zzb()).a();
        d.b a121 = d.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzay zzay121 = new zzay();
        zzay121.zza(123);
        zzbq = a121.b(zzay121.zzb()).a();
        d.b a122 = d.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzay zzay122 = new zzay();
        zzay122.zza(124);
        zzbr = a122.b(zzay122.zzb()).a();
        d.b a123 = d.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzay zzay123 = new zzay();
        zzay123.zza(ISO781611.SMT_TAG);
        zzbs = a123.b(zzay123.zzb()).a();
        d.b a124 = d.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzay zzay124 = new zzay();
        zzay124.zza(126);
        zzbt = a124.b(zzay124.zzb()).a();
        d.b a125 = d.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzay zzay125 = new zzay();
        zzay125.zza(CertificateBody.profileType);
        zzbu = a125.b(zzay125.zzb()).a();
        d.b a126 = d.a("subjectSegmentationOptionalModuleLogEvent");
        zzay zzay126 = new zzay();
        zzay126.zza(128);
        zzbv = a126.b(zzay126.zzb()).a();
        d.b a127 = d.a("documentScannerUiModuleScreenViewEvent");
        zzay zzay127 = new zzay();
        zzay127.zza(129);
        zzbw = a127.b(zzay127.zzb()).a();
        d.b a128 = d.a("documentScannerUiModuleScreenClickEvent");
        zzay zzay128 = new zzay();
        zzay128.zza(ISO781611.BIOMETRIC_SUBTYPE_TAG);
        zzbx = a128.b(zzay128.zzb()).a();
        d.b a129 = d.a("documentScannerUiModuleScreenErrorEvent");
        zzay zzay129 = new zzay();
        zzay129.zza(ISO781611.CREATION_DATE_AND_TIME_TAG);
        zzby = a129.b(zzay129.zzb()).a();
    }

    private zzgp() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzmy zzmy = (zzmy) obj;
        f fVar = (f) obj2;
        fVar.add(zzb, zzmy.zzf());
        fVar.add(zzc, zzmy.zzd());
        fVar.add(zzd, (Object) null);
        fVar.add(zze, (Object) null);
        fVar.add(zzf, zzmy.zze());
        fVar.add(zzg, (Object) null);
        fVar.add(zzh, (Object) null);
        fVar.add(zzi, (Object) null);
        fVar.add(zzj, (Object) null);
        fVar.add(zzk, (Object) null);
        fVar.add(zzl, (Object) null);
        fVar.add(zzm, (Object) null);
        fVar.add(zzn, (Object) null);
        fVar.add(zzo, (Object) null);
        fVar.add(zzp, (Object) null);
        fVar.add(zzq, (Object) null);
        fVar.add(zzr, (Object) null);
        fVar.add(zzs, (Object) null);
        fVar.add(zzt, (Object) null);
        fVar.add(zzu, (Object) null);
        fVar.add(zzv, (Object) null);
        fVar.add(zzw, (Object) null);
        fVar.add(zzx, (Object) null);
        fVar.add(zzy, (Object) null);
        fVar.add(zzz, (Object) null);
        fVar.add(zzA, (Object) null);
        fVar.add(zzB, (Object) null);
        fVar.add(zzC, (Object) null);
        fVar.add(zzD, (Object) null);
        fVar.add(zzE, (Object) null);
        fVar.add(zzF, (Object) null);
        fVar.add(zzG, (Object) null);
        fVar.add(zzH, (Object) null);
        fVar.add(zzI, (Object) null);
        fVar.add(zzJ, (Object) null);
        fVar.add(zzK, (Object) null);
        fVar.add(zzL, (Object) null);
        fVar.add(zzM, (Object) null);
        fVar.add(zzN, zzmy.zzb());
        fVar.add(zzO, zzmy.zza());
        fVar.add(zzP, (Object) null);
        fVar.add(zzQ, (Object) null);
        fVar.add(zzR, (Object) null);
        fVar.add(zzS, (Object) null);
        fVar.add(zzT, (Object) null);
        fVar.add(zzU, (Object) null);
        fVar.add(zzV, (Object) null);
        fVar.add(zzW, (Object) null);
        fVar.add(zzX, (Object) null);
        fVar.add(zzY, (Object) null);
        fVar.add(zzZ, (Object) null);
        fVar.add(zzaa, (Object) null);
        fVar.add(zzab, zzmy.zzc());
        fVar.add(zzac, (Object) null);
        fVar.add(zzad, (Object) null);
        fVar.add(zzae, (Object) null);
        fVar.add(zzaf, (Object) null);
        fVar.add(zzag, (Object) null);
        fVar.add(zzah, (Object) null);
        fVar.add(zzai, (Object) null);
        fVar.add(zzaj, (Object) null);
        fVar.add(zzak, (Object) null);
        fVar.add(zzal, (Object) null);
        fVar.add(zzam, (Object) null);
        fVar.add(zzan, (Object) null);
        fVar.add(zzao, (Object) null);
        fVar.add(zzap, (Object) null);
        fVar.add(zzaq, (Object) null);
        fVar.add(zzar, (Object) null);
        fVar.add(zzas, (Object) null);
        fVar.add(zzat, (Object) null);
        fVar.add(zzau, (Object) null);
        fVar.add(zzav, (Object) null);
        fVar.add(zzaw, (Object) null);
        fVar.add(zzax, (Object) null);
        fVar.add(zzay, (Object) null);
        fVar.add(zzaz, (Object) null);
        fVar.add(zzaA, (Object) null);
        fVar.add(zzaB, (Object) null);
        fVar.add(zzaC, (Object) null);
        fVar.add(zzaD, (Object) null);
        fVar.add(zzaE, (Object) null);
        fVar.add(zzaF, (Object) null);
        fVar.add(zzaG, (Object) null);
        fVar.add(zzaH, (Object) null);
        fVar.add(zzaI, (Object) null);
        fVar.add(zzaJ, (Object) null);
        fVar.add(zzaK, (Object) null);
        fVar.add(zzaL, (Object) null);
        fVar.add(zzaM, (Object) null);
        fVar.add(zzaN, (Object) null);
        fVar.add(zzaO, (Object) null);
        fVar.add(zzaP, (Object) null);
        fVar.add(zzaQ, (Object) null);
        fVar.add(zzaR, (Object) null);
        fVar.add(zzaS, (Object) null);
        fVar.add(zzaT, (Object) null);
        fVar.add(zzaU, (Object) null);
        fVar.add(zzaV, (Object) null);
        fVar.add(zzaW, (Object) null);
        fVar.add(zzaX, (Object) null);
        fVar.add(zzaY, (Object) null);
        fVar.add(zzaZ, (Object) null);
        fVar.add(zzba, (Object) null);
        fVar.add(zzbb, (Object) null);
        fVar.add(zzbc, (Object) null);
        fVar.add(zzbd, (Object) null);
        fVar.add(zzbe, (Object) null);
        fVar.add(zzbf, (Object) null);
        fVar.add(zzbg, (Object) null);
        fVar.add(zzbh, (Object) null);
        fVar.add(zzbi, (Object) null);
        fVar.add(zzbj, (Object) null);
        fVar.add(zzbk, (Object) null);
        fVar.add(zzbl, (Object) null);
        fVar.add(zzbm, (Object) null);
        fVar.add(zzbn, (Object) null);
        fVar.add(zzbo, (Object) null);
        fVar.add(zzbp, (Object) null);
        fVar.add(zzbq, (Object) null);
        fVar.add(zzbr, (Object) null);
        fVar.add(zzbs, (Object) null);
        fVar.add(zzbt, (Object) null);
        fVar.add(zzbu, (Object) null);
        fVar.add(zzbv, (Object) null);
        fVar.add(zzbw, (Object) null);
        fVar.add(zzbx, (Object) null);
        fVar.add(zzby, (Object) null);
    }
}
