package com.google.android.gms.internal.mlkit_common;

import com.fis.ekyc.nfc.build_in.eidparser.cbeff.ISO781611;
import com.fis.ekyc.nfc.build_in.eidparser.lds.LDSFile;

public enum zzmu implements zzba {
    NO_ERROR(0),
    INCOMPATIBLE_INPUT(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    MEDIAPIPE_ERROR(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(LDSFile.EF_DG5_TAG),
    NO_NETWORK_CONNECTION(LDSFile.EF_DG6_TAG),
    METERED_NETWORK(LDSFile.EF_DG7_TAG),
    DOWNLOAD_FAILED(LDSFile.EF_DG8_TAG),
    MODEL_INFO_DOWNLOAD_UNSUCCESSFUL_HTTP_STATUS(LDSFile.EF_DG9_TAG),
    MODEL_INFO_DOWNLOAD_NO_HASH(LDSFile.EF_DG10_TAG),
    MODEL_INFO_DOWNLOAD_CONNECTION_FAILED(LDSFile.EF_DG11_TAG),
    NO_VALID_MODEL(LDSFile.EF_DG12_TAG),
    LOCAL_MODEL_INVALID(LDSFile.EF_DG13_TAG),
    REMOTE_MODEL_INVALID(LDSFile.EF_DG14_TAG),
    REMOTE_MODEL_LOADER_ERROR(LDSFile.EF_DG15_TAG),
    REMOTE_MODEL_LOADER_LOADS_NO_MODEL(LDSFile.EF_DG16_TAG),
    SMART_REPLY_LANG_ID_DETECTAION_FAILURE(113),
    MODEL_NOT_REGISTERED(114),
    MODEL_TYPE_MISUSE(ISO781611.DISCRETIONARY_DATA_FOR_PAYLOAD_CONSTRUCTED_TAG),
    MODEL_HASH_MISMATCH(116),
    OPTIONAL_MODULE_NOT_AVAILABLE(201),
    OPTIONAL_MODULE_INIT_ERROR(202),
    OPTIONAL_MODULE_INFERENCE_ERROR(203),
    OPTIONAL_MODULE_RELEASE_ERROR(204),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(205),
    NATIVE_LIBRARY_LOAD_ERROR(206),
    OPTIONAL_MODULE_CREATE_ERROR(207),
    CAMERAX_SOURCE_ERROR(301),
    CAMERA1_SOURCE_CANT_START_ERROR(302),
    CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(303),
    CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(304),
    CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(305),
    CODE_SCANNER_UNAVAILABLE(400),
    CODE_SCANNER_CANCELLED(401),
    CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(402),
    CODE_SCANNER_APP_NAME_UNAVAILABLE(403),
    CODE_SCANNER_TASK_IN_PROGRESS(404),
    CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(405),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(406),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(407),
    LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(500),
    LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(501),
    PERMISSION_DENIED(600),
    CANCELLED(601),
    GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(602),
    LOW_MEMORY(603),
    UNKNOWN_ERROR(9999);
    
    private final int zzad;

    private zzmu(int i) {
        this.zzad = i;
    }

    public final int zza() {
        return this.zzad;
    }
}
